# -*- coding: utf-8 -*-
"""
Life Event Havuzu Genişletmesi — GDD v5 Faz 2C
Yaş 18+ içerik çölünü dolduran 70 yeni event:
  18-30 yetişkinlik: 25 · 30-50 orta yaş: 28 · 50+ yaşlılık: 17
Şema life_events.LIFE_EVENTS ile birebir aynı.
"""

LIFE_EVENTS_V2 = [
    # ═════════════════════════════════════════
    # 🧑 YETİŞKİNLİK (18-30) — 25 event
    # ═════════════════════════════════════════
    {
        "id": "v2_ilk_ev_teklifi",
        "title": "Komşunun Arsa Teklifi",
        "description": "Yaşlı komşun arazisini satıyor: 'Sana yarı fiyatına veririm, yeter ki köylüye gitsin.'",
        "icon": "🏡",
        "conditions": {"age_min": 18, "age_max": 30, "money_min": 150},
        "choices": [
            {"text": "Teklifi kabul et", "effects": {"money": -150, "reputation": 4}, "result": "Arsa senin. Komşun gözleri dolu dolu anahtarı verdi."},
            {"text": "Pazarlık yap", "effects": {"money": -100, "trade": 1, "reputation": -2}, "result": "Daha da düşürdün. Kârlı ama komşun kırgın."},
            {"text": "Reddet", "effects": {}, "result": "Arsa bir tüccara gitti. Komşun küstü."},
        ],
    },
    {
        "id": "v2_asker_cagrisi",
        "title": "Sefer Çağrısı",
        "description": "Tellal bağırıyor: sultan orduya gönüllü topluyor. Sefere katılanlara ganimet payı sözü var.",
        "icon": "⚔️",
        "conditions": {"age_min": 18, "age_max": 30},
        "choices": [
            {"text": "Gönüllü yaz", "effects": {"combat": 2, "money": 40, "health": -15, "fame": 5}, "result": "Seferden yara ve ganimetle döndün. Adın asker arasında geçiyor."},
            {"text": "Bedel öde, muaf ol", "effects": {"money": -50}, "result": "Kesenle kurtuldun. Bazıları arkandan 'korkak' dedi."},
            {"text": "Saklan", "effects": {"crime": 8, "fear": 3}, "result": "Devriyeler seni aradı. Bir hafta samanlıkta yattın."},
        ],
    },
    {
        "id": "v2_kumarhane",
        "title": "Hanın Arka Odası",
        "description": "Handa zar masası dönüyor. Kasada ciddi para var; eller terli, gözler parlak.",
        "icon": "🎲",
        "conditions": {"age_min": 18, "age_max": 35, "money_min": 30},
        "choices": [
            {"text": "Masaya otur, büyük oyna", "effects": {"money": 60, "crime": 3}, "result": "Zarlar senden yana döndü! Cebin doldu, ama kumarhanenin gözü üstünde."},
            {"text": "Küçük oyna, erken kalk", "effects": {"money": 10}, "result": "Az kazandın ama kesen ve onurun yerinde."},
            {"text": "Oynama, izle", "effects": {"intelligence": 1}, "result": "Hile yapanın bileğini gördün. Bu bilgi bir gün lazım olur."},
        ],
    },
    {
        "id": "v2_yangin_komsu",
        "title": "Gece Yangını",
        "description": "Komşunun samanlığı alev aldı! Çığlıklar geceyi yırtıyor.",
        "icon": "🔥",
        "conditions": {"age_min": 18, "age_max": 45},
        "choices": [
            {"text": "Ateşe dal, hayvanları kurtar", "effects": {"health": -20, "honor": 8, "reputation": 6}, "result": "Yanık ellerle ama dolu bir vicdanla çıktın. Köy seni konuşuyor."},
            {"text": "Kova zinciri kur", "effects": {"social": 1, "reputation": 3}, "result": "Soğukkanlılığın yangını sınırladı. Akıllıca."},
            {"text": "Kendi evini koru", "effects": {"honor": -3}, "result": "Senin çatın sağlam ama komşunun bakışı soğuk."},
        ],
    },
    {
        "id": "v2_tuccar_ortaklik",
        "title": "Ortaklık Teklifi",
        "description": "Tanıdık bir tüccar el sıkışmak istiyor: 'Sermayeni koy, kârı bölüşelim.'",
        "icon": "🤝",
        "conditions": {"age_min": 18, "age_max": 40, "money_min": 100},
        "choices": [
            {"text": "Ortak ol", "effects": {"money": 80, "trade": 1}, "result": "İlk sezon bereketliydi. Payın elinde."},
            {"text": "Önce defterlerini iste", "effects": {"intelligence": 1, "trade": 1}, "result": "Defterde delikler buldun ve uzak durdun. İyi ki bakmışsın."},
            {"text": "Reddet", "effects": {}, "result": "Tüccar başkasıyla anlaştı. Kısmet."},
        ],
    },
    {
        "id": "v2_dugun_daveti",
        "title": "Zengin Düğünü",
        "description": "Kasabanın ileri gelenlerinden birinin düğününe davetlisin. Herkes orada olacak.",
        "icon": "💍",
        "conditions": {"age_min": 18, "age_max": 40},
        "choices": [
            {"text": "Cömert hediye götür", "effects": {"money": -40, "reputation": 6, "social": 1}, "result": "Hediyene herkes baktı. Artık 'tanınan' birisin."},
            {"text": "Mütevazı katıl", "effects": {"social": 1}, "result": "Güzel bir gece; birkaç yeni tanıdık edindin."},
            {"text": "Gitme", "effects": {"reputation": -3}, "result": "Yokluğun fark edildi ve not edildi."},
        ],
    },
    {
        "id": "v2_yol_haydudu",
        "title": "Yol Kesen",
        "description": "Issız yolda önüne bir gölge çıktı: 'Kesen ya da canın.'",
        "icon": "🗡️",
        "conditions": {"age_min": 18, "age_max": 50},
        "choices": [
            {"text": "Dövüş", "effects": {"combat": 2, "health": -15, "fame": 3}, "result": "Haydut kaçtı; bıçağı hatıra kaldı. Hikâyen handa anlatılıyor."},
            {"text": "Keseni ver", "effects": {"money": -30}, "result": "Para gitti, can kaldı. Mantıklı bir takas."},
            {"text": "Blöf yap: 'Arkamda muhafızlar var'", "effects": {"charisma": 1}, "result": "Haydut etrafa bakındı ve kayboldu. Yüreğin ağzında ama kesen cebinde."},
        ],
    },
    {
        "id": "v2_eski_dost_borc",
        "title": "Eski Dostun Borcu",
        "description": "Çocukluk arkadaşın kapında: 'Bir borcum var, ödeyemezsem parmaklarımı kırarlar.'",
        "icon": "🫴",
        "conditions": {"age_min": 18, "age_max": 45, "money_min": 60},
        "choices": [
            {"text": "Borcunu kapat", "effects": {"money": -60, "honor": 5}, "result": "Gözlerindeki minnet paradan değerliydi. Belki bir gün öder."},
            {"text": "Yarısını ver", "effects": {"money": -30, "honor": 2}, "result": "Kalanı için zaman kazandı. Az da olsa nefes aldırdın."},
            {"text": "'Kendi batağın' de", "effects": {"honor": -4}, "result": "Kapıyı kapattın. Bir ay sonra kolu askıda gördün onu."},
        ],
    },
    {
        "id": "v2_lonca_daveti",
        "title": "Lonca Sofrası",
        "description": "Meslek loncasının yıllık yemeğine çağrıldın. Ustalar seni süzecek.",
        "icon": "🍖",
        "conditions": {"age_min": 18, "age_max": 35},
        "choices": [
            {"text": "Sofrada parlamaya çalış", "effects": {"charisma": 1, "social": 1, "reputation": 3}, "result": "Anlattığın hikâye sofrayı güldürdü. Ustalar adını sordu."},
            {"text": "Az konuş, çok dinle", "effects": {"intelligence": 1, "crafting": 1}, "result": "Ustaların sohbetinden zanaat sırları kaptın."},
            {"text": "Gitme", "effects": {"reputation": -2}, "result": "Boş sandalyen konuşuldu."},
        ],
    },
    {
        "id": "v2_pazar_kavgasi",
        "title": "Pazar Kavgası",
        "description": "Pazarda iki satıcı birbirine girdi; tezgâhlar devriliyor, kalabalık büyüyor.",
        "icon": "🥊",
        "conditions": {"age_min": 18, "age_max": 45},
        "choices": [
            {"text": "Araya gir, ayır", "effects": {"health": -8, "reputation": 5, "honor": 3}, "result": "Yumruk yedin ama kavgayı bitirdin. Pazarcılar sana borçlu."},
            {"text": "Devrilen maldan topla", "effects": {"money": 15, "crime": 6, "honor": -5}, "result": "Karışıklıkta birkaç şey cebe girdi. Gören oldu mu acaba?"},
            {"text": "Uzaktan izle", "effects": {}, "result": "Muhafızlar geldi, kavga bitti. Sıradan bir gün."},
        ],
    },
    {
        "id": "v2_gizemli_yabanci",
        "title": "Gizemli Yabancı",
        "description": "Handa kapüşonlu bir yabancı masana oturdu: 'Bir mektubu yerine ulaştırır mısın? Sorularsız.'",
        "icon": "🕵️",
        "conditions": {"age_min": 18, "age_max": 40},
        "choices": [
            {"text": "Kabul et", "effects": {"money": 50, "crime": 5, "fear": 2}, "result": "Mektup teslim edildi, kese doldu. İçinde ne vardı, asla bilmeyeceksin."},
            {"text": "Mektubu aç, sonra karar ver", "effects": {"intelligence": 1, "crime": 3}, "result": "Şifreliydi. Ama mühür... o mührü bir yerden tanıyorsun."},
            {"text": "Reddet", "effects": {}, "result": "Yabancı sessizce kayboldu. Belki de en iyisi buydu."},
        ],
    },
    {
        "id": "v2_hasat_yarismasi",
        "title": "Hasat Yarışması",
        "description": "Köyde yıllık hasat yarışması: en iyi ürün ödül alacak, herkes iddialı.",
        "icon": "🌾",
        "conditions": {"age_min": 18, "age_max": 50, "location_kind": "köy"},
        "choices": [
            {"text": "En iyi ürününle katıl", "effects": {"money": 25, "reputation": 4}, "result": "Ürünün dillere düştü; ödül ve alkış senin."},
            {"text": "Rakibin ürününe göz at", "effects": {"intelligence": 1, "crime": 2}, "result": "Tohum sırrını çözdün — ama yöntemin pek dürüst sayılmaz."},
            {"text": "Sadece şenliğe katıl", "effects": {"social": 1}, "result": "Yiyip içtin, güldün. Bazen kazanmak gerekmiyor."},
        ],
    },
    {
        "id": "v2_kuyu_tartismasi",
        "title": "Kuyu Nöbeti",
        "description": "Kurak haftalar; köy kuyusunda kuyruk uzun ve sabırlar kısa. Sıra tartışması büyüyor.",
        "icon": "🪣",
        "conditions": {"age_min": 18, "age_max": 55, "location_kind": "köy"},
        "choices": [
            {"text": "Nöbet çizelgesi öner", "effects": {"intelligence": 1, "reputation": 5}, "result": "Çizelgen kabul gördü. Kuyu başı sakinleşti, adın 'akıllı'ya çıktı."},
            {"text": "Sıranı zorla öne al", "effects": {"crime": 4, "fear": 2, "reputation": -4}, "result": "Suyu aldın ama bakışlar bıçak gibiydi."},
            {"text": "Sıranı yaşlılara ver", "effects": {"honor": 4, "reputation": 3}, "result": "Bir teşekkür duası bazen sudan kıymetlidir."},
        ],
    },
    {
        "id": "v2_ucuz_mal",
        "title": "Şüpheli Ucuzluk",
        "description": "Bir seyyar satıcı kervan malını yarı fiyatına satıyor. 'Acele et, akşama yokum' diyor.",
        "icon": "📦",
        "conditions": {"age_min": 18, "age_max": 50, "money_min": 40},
        "choices": [
            {"text": "Hepsini kapat", "effects": {"money": -40, "trade": 1, "crime": 4}, "result": "Malı üçe katlayıp sattın. Sonradan duydun: mal çalıntıymış."},
            {"text": "Sorgula: 'Bu mal nereden?'", "effects": {"intelligence": 1}, "result": "Kem küm etti ve tezgâhı topladı. İçgüdün doğruymuş."},
            {"text": "Muhafızlara bildir", "effects": {"reputation": 4, "honor": 3}, "result": "Mal çalıntı çıktı. Kervancılar sana teşekkür etti."},
        ],
    },
    {
        "id": "v2_gece_nobetcisi",
        "title": "Gece Nöbeti Teklifi",
        "description": "Muhtar gece bekçiliği için adam arıyor: 'Az para ama köyün duası seninle.'",
        "icon": "🏮",
        "conditions": {"age_min": 18, "age_max": 45},
        "choices": [
            {"text": "Nöbeti üstlen", "effects": {"money": 15, "stamina": 1, "reputation": 3}, "result": "Soğuk geceler ama huzurlu sabahlar. Köy sana güveniyor."},
            {"text": "Paraya çalış: ücret iste", "effects": {"money": 25, "reputation": -2}, "result": "Ücretini aldın ama 'paragöz' yaftası da cabası."},
            {"text": "Reddet", "effects": {}, "result": "Başkası üstlendi. Hayat devam ediyor."},
        ],
    },
    {
        "id": "v2_dilenci_cocuk",
        "title": "Dilenci Çocuk",
        "description": "Pazar girişinde bir çocuk avucunu açmış: yalınayak, gözleri büyük.",
        "icon": "🥺",
        "conditions": {"age_min": 18, "age_max": 60},
        "choices": [
            {"text": "Para ver", "effects": {"money": -5, "honor": 2}, "result": "Avucuna sıkıştırdın. Koşarak kayboldu — umarım ekmeğe gider."},
            {"text": "Yemek ısmarla, konuş", "effects": {"money": -8, "honor": 4, "intelligence": 1}, "result": "Hikâyesini dinledin: savaş yetimiymiş. Adresini hatırında tut."},
            {"text": "Geç git", "effects": {}, "result": "Adımlarını hızlandırdın. Şehir böyle, herkes kendi derdinde."},
        ],
    },
    {
        "id": "v2_silah_satici",
        "title": "Eski Asker'in Kılıcı",
        "description": "Yaşlı bir asker kılıcını satıyor: 'Üç savaş gördü bu çelik. Artık benim kolum kaldırmıyor.'",
        "icon": "🗡️",
        "conditions": {"age_min": 18, "age_max": 40, "money_min": 50},
        "choices": [
            {"text": "Satın al", "effects": {"money": -50, "add_item": {"item": "silah", "qty": 1}}, "result": "Kabzasında üç çentik var. Hikâyesiyle birlikte artık senin."},
            {"text": "Hikâyesini dinle, alma", "effects": {"intelligence": 1, "combat": 1}, "result": "Üç saatlik savaş dersi — bedava. Kılıçtan değerli."},
            {"text": "İlgilenme", "effects": {}, "result": "Yaşlı asker tezgâhını topladı. Kılıç başkasının oldu."},
        ],
    },
    {
        "id": "v2_yarali_yolcu",
        "title": "Yaralı Yolcu",
        "description": "Yol kenarında kanlar içinde bir yolcu: 'Beni soydular... su...'",
        "icon": "🩸",
        "conditions": {"age_min": 18, "age_max": 60},
        "choices": [
            {"text": "Yardım et, köye taşı", "effects": {"health": -5, "honor": 6, "reputation": 4}, "result": "Adam hayatta kaldı. Meğer varlıklı bir tüccarmış — borcunu unutmayacak."},
            {"text": "Su ver, yoluna devam et", "effects": {"honor": 1}, "result": "Elinden geleni yaptın. Gerisi kaderin işi."},
            {"text": "Ceplerini yokla", "effects": {"money": 20, "crime": 10, "honor": -8}, "result": "Baygın adamın kesesini aldın. Gece aynaya bakamadın."},
        ],
    },
    {
        "id": "v2_sarhos_kavga",
        "title": "Meyhane Sataşması",
        "description": "Sarhoşun biri omzuna çarpıp bağırdı: 'Önüne baksana!' Meyhane sustu, herkes size bakıyor.",
        "icon": "🍺",
        "conditions": {"age_min": 18, "age_max": 45},
        "choices": [
            {"text": "Yumruğu bas", "effects": {"combat": 1, "health": -10, "crime": 5, "fear": 3}, "result": "Masalar devrildi. Kazandın ama meyhaneci seni kapı dışarı etti."},
            {"text": "'Pardon dostum' de, içkisini ısmarla", "effects": {"money": -5, "charisma": 1, "social": 1}, "result": "Sarhoş kadehini kaldırdı: 'İşte adam böyle olur!' Gece güzel bitti."},
            {"text": "Sessizce çık", "effects": {}, "result": "Kapı arkandan kapandı. Bazen en cesur hamle çekilmektir."},
        ],
    },
    {
        "id": "v2_kayip_kese",
        "title": "Düşen Kese",
        "description": "Önünde yürüyen tüccarın belinden kese düştü; fark etmedi. İçi dolu görünüyor.",
        "icon": "👛",
        "conditions": {"age_min": 18, "age_max": 60},
        "choices": [
            {"text": "Koşup geri ver", "effects": {"honor": 5, "reputation": 4, "money": 10}, "result": "Tüccar şaşırdı ve bahşiş verdi: 'Dürüst adam kıtlığında değerlisin.'"},
            {"text": "Cebe at", "effects": {"money": 45, "crime": 8, "honor": -6}, "result": "Kimse görmedi... sandın. Köşedeki dilenci hâriç."},
            {"text": "Seslen ama yaklaşma", "effects": {"honor": 2}, "result": "Tüccar kesesini aldı, başıyla selamladı. Temiz iş."},
        ],
    },
    {
        "id": "v2_at_yarisi",
        "title": "Panayır At Yarışı",
        "description": "Panayırda at yarışı var. Bahisçiler bağırıyor; favori belli ama bir de zayıf görünen yağız var...",
        "icon": "🐎",
        "conditions": {"age_min": 18, "age_max": 50, "money_min": 20},
        "choices": [
            {"text": "Favoriye oyna", "effects": {"money": 10}, "result": "Favori kazandı; küçük ama garanti kâr."},
            {"text": "Yağıza oyna", "effects": {"money": 50}, "result": "Yağız rüzgâr gibi geçti! Bahisçinin suratı, senin kesen şenlendi."},
            {"text": "Oynamadan izle", "effects": {"social": 1}, "result": "Yarış güzeldi, dostlarla gülüştünüz. Kesen de yerinde."},
        ],
    },
    {
        "id": "v2_usta_azari",
        "title": "Ustanın Azarı",
        "description": "İşinde küçük bir hata yaptın; ustan herkesin içinde azarladı. Yüzün kızarıyor.",
        "icon": "😤",
        "conditions": {"age_min": 18, "age_max": 30},
        "choices": [
            {"text": "Sessizce dinle, hatandan öğren", "effects": {"crafting": 2, "intelligence": 1}, "result": "Yutkundun ama dersi aldın. Bir daha aynı hatayı yapmadın."},
            {"text": "Kendini savun", "effects": {"charisma": 1, "reputation": -2}, "result": "Haklı çıktın ama usta bunu unutmaz. Dik başlısın."},
            {"text": "İşi bırak, çık git", "effects": {"honor": -2, "money": -10}, "result": "Kapıyı çarptın. Gururun kurtuldu, haftalığın yandı."},
        ],
    },
    {
        "id": "v2_evlilik_baskisi",
        "title": "Görücü Baskını",
        "description": "Akrabalar toplandı: 'Yaşın geçiyor! Sana güzel bir kısmet bulduk, bir görsen...'",
        "icon": "👵",
        "conditions": {"age_min": 20, "age_max": 35, "no_spouse": True},
        "choices": [
            {"text": "Bir tanışmaktan ne çıkar", "effects": {"social": 1, "charisma": 1}, "result": "Tanıştınız. Fena değildi... belki de akrabalar haklı?"},
            {"text": "'Kendi kısmetimi kendim bulurum'", "effects": {"charisma": 1, "reputation": -2}, "result": "Sofra buz kesti. Halaların bakışı bir hafta sürdü."},
            {"text": "Bahane uydur, kaç", "effects": {}, "result": "Bu seferlik kurtuldun. Ama onlar pes etmez, bilirsin."},
        ],
    },
    {
        "id": "v2_vergi_tahsildari",
        "title": "Tahsildarın Hatası",
        "description": "Vergi tahsildarı yanlış hesapladı — senin lehine. Fark cebinde kalabilir.",
        "icon": "📜",
        "conditions": {"age_min": 18, "age_max": 60, "money_min": 20},
        "choices": [
            {"text": "Hatayı söyle", "effects": {"money": -15, "honor": 5, "reputation": 3}, "result": "Tahsildar şaşkına döndü: 'İlk kez biri kendi aleyhine itiraz ediyor.' Adın deftere not edildi — iyi anlamda."},
            {"text": "Sus, farkı cebe at", "effects": {"money": 15, "crime": 3}, "result": "Kimse fark etmedi. Şimdilik."},
        ],
    },
    {
        "id": "v2_irgat_grevi",
        "title": "İrgatların İsyanı",
        "description": "Tarla irgatları ücret azlığından iş bıraktı. Ağa kuduruyor; irgatlar destek bekliyor.",
        "icon": "✊",
        "conditions": {"age_min": 18, "age_max": 45},
        "choices": [
            {"text": "İrgatların yanında dur", "effects": {"honor": 5, "reputation": 4, "social": 1}, "result": "Kalabalık büyüyünce ağa geri adım attı. Ücretler düzeldi; adın 'halktan yana' yazıldı."},
            {"text": "Arabuluculuk yap", "effects": {"charisma": 1, "intelligence": 1, "reputation": 3}, "result": "İki tarafı masaya oturttun. Orta yol bulundu; iki taraf da sana borçlu."},
            {"text": "Ağanın safında dur", "effects": {"money": 25, "reputation": -5, "honor": -3}, "result": "Ağa keseni doldurdu. İrgatların bakışları ise bedava değildi."},
        ],
    },

    # ═════════════════════════════════════════
    # 🧔 ORTA YAŞ (30-50) — 28 event
    # ═════════════════════════════════════════
    {
        "id": "v2_bel_agrisi",
        "title": "Bel Sancısı",
        "description": "Sabah yataktan kalkarken belin tutuldu. Gençlikte böyle şeyler olmazdı...",
        "icon": "🦴",
        "conditions": {"age_min": 35, "age_max": 55},
        "choices": [
            {"text": "Şifacıya git", "effects": {"money": -20, "health": 10}, "result": "Merhem ve istirahat. Bir haftada düzeldin."},
            {"text": "Boşver, çalışmaya devam", "effects": {"health": -10, "stamina": 1}, "result": "Diş sıktın. Beden alıştı ama geceleri sızlıyor."},
            {"text": "İşi yavaşlat, dinlen", "effects": {"money": -10, "health": 5}, "result": "Kazanç azaldı ama belin düzeldi. Yaşlanmak böyle bir şey."},
        ],
    },
    {
        "id": "v2_cirak_istegi",
        "title": "Çırak Adayı",
        "description": "Komşunun oğlu kapında: 'Usta, beni yanına alır mısın? Babam rica etti.'",
        "icon": "🧒",
        "conditions": {"age_min": 30, "age_max": 55},
        "choices": [
            {"text": "Çırak al, öğret", "effects": {"crafting": 1, "reputation": 5, "money": -5}, "result": "Eli yatkın çıktı. Bir gün senin adını yaşatacak."},
            {"text": "Sınav yap, sonra karar ver", "effects": {"intelligence": 1}, "result": "Üç günlük denemede sabrını ölçtün. İyi karar — aceleci ama hevesli."},
            {"text": "Reddet: 'Vaktim yok'", "effects": {"reputation": -3}, "result": "Komşunla aranıza mesafe girdi."},
        ],
    },
    {
        "id": "v2_miras_kavgasi_akraba",
        "title": "Akraba Miras Kavgası",
        "description": "Uzak bir akraba öldü; mirası için kuzenler birbirine girdi. Sen de hak sahibisin.",
        "icon": "⚖️",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Hakkını sonuna kadar savun", "effects": {"money": 60, "reputation": -3}, "result": "Payını aldın ama aile sofraları artık gergin."},
            {"text": "Uzlaştırıcı ol", "effects": {"charisma": 1, "reputation": 5, "money": 20}, "result": "Herkes payına razı oldu. 'İyi ki vardın' dediler."},
            {"text": "Payından feragat et", "effects": {"honor": 6, "reputation": 4}, "result": "'Kavgalı ekmek yenmez' dedin. Sözün mecliste anlatılıyor."},
        ],
    },
    {
        "id": "v2_eski_rakip",
        "title": "Eski Rakip Düşkün",
        "description": "Gençlikte seninle yarışan adam şimdi pazarda el açıyor. Gözleriniz buluştu.",
        "icon": "🪞",
        "conditions": {"age_min": 35, "age_max": 60},
        "choices": [
            {"text": "Yanına otur, yemek ısmarla", "effects": {"money": -10, "honor": 6}, "result": "Eski günleri konuştunuz. Giderken elini sıktı: 'Sen hep büyüktün.'"},
            {"text": "Sadaka verip geç", "effects": {"money": -3, "honor": 1}, "result": "Para avucuna düştü; ikiniz de gözlerinizi kaçırdınız."},
            {"text": "Görmezden gel", "effects": {"honor": -3}, "result": "Hızla yürüdün. O görüntü zihnine kazındı."},
        ],
    },
    {
        "id": "v2_cocugun_kavgasi",
        "title": "Çocuğun Kavga Etmiş",
        "description": "Komşu kapıda: 'Senin çocuk bizimkini dövmüş!' Çocuğun ise 'O başlattı' diyor.",
        "icon": "👊",
        "conditions": {"age_min": 30, "age_max": 55, "has_children": True},
        "choices": [
            {"text": "Önce çocuğunu dinle", "effects": {"intelligence": 1, "reputation": 2}, "result": "Meğer bizimki haklıymış: arkadaşını korumuş. Komşuyla konuşunca anlaşıldı."},
            {"text": "Çocuğa herkesin önünde kız", "effects": {"reputation": 2, "honor": -2}, "result": "Komşu yatıştı ama çocuğun gözündeki kırıklık akşama kadar gitmedi."},
            {"text": "Komşuyu ters çevir", "effects": {"reputation": -4, "fear": 2}, "result": "Komşu sustu ama mahallede 'şımarık çocuğun babası/anası' lafı dolaşıyor."},
        ],
    },
    {
        "id": "v2_buyuk_siparis",
        "title": "Büyük Sipariş",
        "description": "Saraydan adam geldi: büyük bir sipariş — ama teslim süresi imkânsıza yakın.",
        "icon": "📋",
        "conditions": {"age_min": 30, "age_max": 55},
        "choices": [
            {"text": "Kabul et, gece gündüz çalış", "effects": {"money": 80, "health": -15, "fame": 5}, "result": "Bitirdin! Ellerin nasır, adın sarayda."},
            {"text": "Yardımcı tut, kârı bölüş", "effects": {"money": 40, "social": 1}, "result": "İş zamanında bitti, kâr azaldı ama dostluk kazandın."},
            {"text": "Reddet: 'Kalitemden ödün vermem'", "effects": {"honor": 3, "reputation": 2}, "result": "Sözün ustalar arasında saygı gördü: 'İşini bilen adam.'"},
        ],
    },
    {
        "id": "v2_sel_baskini",
        "title": "Sel Baskını",
        "description": "Bahar yağmurları dere taşırdı; mahalleyi su bastı. Herkes bir şeyler kurtarmaya çalışıyor.",
        "icon": "🌊",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Komşuların eşyasını kurtar", "effects": {"health": -10, "honor": 6, "reputation": 5}, "result": "Islandın, üşüdün ama üç evin eşyası kurtuldu. Mahalle bunu unutmaz."},
            {"text": "Kendi malını koru", "effects": {"money": 10}, "result": "Senin zararın az oldu. Komşularınki... daha az şanslıydı."},
            {"text": "Sel sonrası ucuza mal topla", "effects": {"money": 30, "honor": -6, "crime": 3}, "result": "Felaketin pazarı da olurmuş. Kazandın ama bakışlar ağır."},
        ],
    },
    {
        "id": "v2_gec_ogrenim",
        "title": "Okuma Hevesi",
        "description": "Pazarda eski bir kitap buldun. İçinden bir ses 'artık çok geç' diyor, diğeri 'asla geç değil'.",
        "icon": "📖",
        "conditions": {"age_min": 35, "age_max": 60},
        "choices": [
            {"text": "Kitabı al, her akşam oku", "effects": {"money": -15, "intelligence": 2}, "result": "Harfler önce dans etti, sonra hizaya geldi. Zihnin gençleşti."},
            {"text": "Çocuğuna al", "effects": {"money": -15, "reputation": 2}, "result": "Çocuğun gözleri parladı. Senin okuyamadığını o okuyacak."},
            {"text": "'Kitap karın doyurmaz' de", "effects": {}, "result": "Kitap tezgâhta kaldı. Belki başka bahar."},
        ],
    },
    {
        "id": "v2_kervan_yatirimi",
        "title": "Kervan Hissesi",
        "description": "Bir kervancı sefere hisse satıyor: 'Dönüşte payını üçe katlarım.' Riskli ama cazip.",
        "icon": "🐪",
        "conditions": {"age_min": 30, "age_max": 55, "money_min": 80},
        "choices": [
            {"text": "Büyük hisse al", "effects": {"money": 70, "trade": 1}, "result": "Kervan sağ salim döndü; payın katlandı!"},
            {"text": "Küçük hisse al", "effects": {"money": 20}, "result": "Az koydun, az kazandın. Uyku düzenin bozulmadı."},
            {"text": "Yatırma", "effects": {}, "result": "Kervan soyuldu! Parasını koyanlar perişan. İçgüdün altın değerinde."},
        ],
    },
    {
        "id": "v2_es_hastaligi",
        "title": "Eşin Hastalığı",
        "description": "Eşin günlerdir ateşler içinde. Şifacı pahalı bir ilaç öneriyor; bir de uzak şehirdeki hekim var.",
        "icon": "💊",
        "conditions": {"age_min": 30, "age_max": 60, "has_spouse": True},
        "choices": [
            {"text": "Pahalı ilacı al", "effects": {"money": -50, "honor": 3}, "result": "İlaç işe yaradı; eşin ayağa kalktı. Para gider, can gelmez."},
            {"text": "Uzak hekime götür", "effects": {"money": -30, "health": -5, "honor": 4}, "result": "Yol zorluydu ama hekim derdi kökünden çözdü."},
            {"text": "Dualarla bekle", "effects": {"honor": -2}, "result": "Haftalar sürdü ama atlattı. Eşinin gözünde bir soru asılı kaldı."},
        ],
    },
    {
        "id": "v2_muhtarlik_adayligi",
        "title": "Muhtarlık Çağrısı",
        "description": "Köylüler kapında: 'Eski muhtar düşkünleşti. Sen aday ol, sana güveniyoruz.'",
        "icon": "🗳️",
        "conditions": {"age_min": 35, "age_max": 60, "reputation_min": 15},
        "choices": [
            {"text": "Aday ol", "effects": {"reputation": 8, "social": 1, "money": -10}, "result": "Meydan kahvesinde söz verdin: 'Kapım hep açık.' Seçim heyecanı başladı."},
            {"text": "Başkasını destekle", "effects": {"reputation": 3, "social": 1}, "result": "Desteklediğin aday kazandı ve sana borçlu kaldı."},
            {"text": "Reddet: 'Benden muhtar olmaz'", "effects": {}, "result": "Köylüler üzüldü ama saygı duydu."},
        ],
    },
    {
        "id": "v2_eski_borclu",
        "title": "Borçlu Geri Döndü",
        "description": "Yıllar önce sana borç takıp kaybolan adam kapında: 'Borcumu ödemeye geldim... faiziyle.'",
        "icon": "💰",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Sadece anaparayı al", "effects": {"money": 40, "honor": 4}, "result": "'Faiz haram' dedin. Adam elini öpecekti neredeyse."},
            {"text": "Faiziyle al", "effects": {"money": 60}, "result": "Hesap hesaptır. Adam ödedi ve gitti — bir daha selam vermedi."},
            {"text": "Borcu bağışla", "effects": {"honor": 7, "reputation": 4}, "result": "'Geçmişte kaldı' dedin. Adamın gözleri doldu; duası peşinden geldi."},
        ],
    },
    {
        "id": "v2_yikilan_dukkan",
        "title": "Fırtına Hasarı",
        "description": "Gece fırtınası iş yerinin çatısını uçurdu. Hasar büyük, kış kapıda.",
        "icon": "🌪️",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Borç al, hemen onar", "effects": {"money": -40, "stamina": 1}, "result": "Bir haftada çatı yenilendi. Borç sıkıyor ama iş dönüyor."},
            {"text": "Kendin onar, yavaş yavaş", "effects": {"health": -10, "crafting": 2, "money": -15}, "result": "Üç hafta sürdü ama her çivisini sen çaktın. Çatı artık kale gibi."},
            {"text": "Komşulardan imece iste", "effects": {"social": 2, "reputation": 3, "money": -10}, "result": "Yarım günde çatı kapandı; akşam herkese çorba kaynattın."},
        ],
    },
    {
        "id": "v2_sehir_daveti",
        "title": "Şehirden İş Teklifi",
        "description": "Şehirden gelen bir usta seni yanına çağırıyor: 'Burada kazandığının üç katı. Ama köyünü bırakacaksın.'",
        "icon": "🏙️",
        "conditions": {"age_min": 30, "age_max": 50, "location_kind": "köy"},
        "choices": [
            {"text": "Teklifi kabul et", "effects": {"money": 50, "reputation": -3}, "result": "Yeni hayat, yeni kazanç. Ama köy meydanını rüyalarında görüyorsun."},
            {"text": "Pazarlık: 'Mevsimlik gelirim'", "effects": {"money": 30, "trade": 1}, "result": "İki dünyanın da tadı sende. Yorucu ama akıllıca."},
            {"text": "Reddet: 'Köküm burada'", "effects": {"honor": 3, "reputation": 4}, "result": "Köylü bunu duyunca yüreklendi: 'Bizimkisi bizi bırakmaz.'"},
        ],
    },
    {
        "id": "v2_gizli_definecix",
        "title": "Define Söylentisi",
        "description": "İhtiyar bir çoban kulağına fısıldadı: 'Harabelerin altında küp dolusu altın var. Ben yaşlandım, sen git.'",
        "icon": "🏺",
        "conditions": {"age_min": 30, "age_max": 55},
        "choices": [
            {"text": "Kazmaya git", "effects": {"health": -10, "money": 35, "fear": 2}, "result": "Küp yoktu ama eski sikkeler vardı! Ve duvardaki o tuhaf yazılar..."},
            {"text": "Çobanla ortak kaz", "effects": {"money": 15, "social": 1}, "result": "İki kişi daha hızlı kazıyor. Az ama gerçek bir pay çıktı."},
            {"text": "Masal deyip geç", "effects": {}, "result": "Bir ay sonra duydun: birileri orada gerçekten bir şeyler bulmuş..."},
        ],
    },
    {
        "id": "v2_lonca_secimi",
        "title": "Lonca Seçimi",
        "description": "Lonca başkanlığı için seçim var. İki aday da senin desteğini istiyor — oyların kilidi sende.",
        "icon": "🏛️",
        "conditions": {"age_min": 35, "age_max": 60},
        "choices": [
            {"text": "Reformcu genci destekle", "effects": {"reputation": 4, "social": 1}, "result": "Genç kazandı; loncaya taze kan geldi. Sana 'bey yapıcı' diyorlar."},
            {"text": "Tecrübeli ustayı destekle", "effects": {"reputation": 3, "crafting": 1}, "result": "Usta kazandı; istikrar sürdü. Minnetini esirgemedi."},
            {"text": "Tarafsız kal", "effects": {}, "result": "Seçim bitti; iki taraf da sana mesafeli artık. Tarafsızlığın bedeli."},
        ],
    },
    {
        "id": "v2_yetim_emanet",
        "title": "Yetim Emaneti",
        "description": "Ölen bir dostun çocuğu kapıda; vasiyeti sana emanet etmiş: 'Ona göz kulak ol.'",
        "icon": "🧸",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Evine al, evladın gibi büyüt", "effects": {"money": -20, "honor": 8, "reputation": 5}, "result": "Sofraya bir tabak daha kondu. Hayır dualar eksilmeyecek."},
            {"text": "Çıraklığa yerleştir, gözet", "effects": {"honor": 4, "social": 1}, "result": "İyi bir ustaya verdin; her ay yoklarsın. Dostun rahat uyusun."},
            {"text": "Akrabalarına yolla", "effects": {"honor": -3}, "result": "Çocuk uzak akrabalara gitti. Dostunun yüzü gözünün önünden gitmiyor."},
        ],
    },
    {
        "id": "v2_rakip_iflasi",
        "title": "Rakibin İflası",
        "description": "Yıllardır rekabet ettiğin esnaf iflas etti. Tezgâhı ve müşterileri ortada kaldı.",
        "icon": "📉",
        "conditions": {"age_min": 30, "age_max": 55},
        "choices": [
            {"text": "Tezgâhını ucuza al", "effects": {"money": -30, "trade": 2}, "result": "İşini büyüttün. Rakibin giderken 'hayrını gör' dedi — yarısı içten."},
            {"text": "Ona iş teklif et", "effects": {"reputation": 6, "honor": 5, "social": 1}, "result": "Dünkü rakibin bugün ustabaşın. Çarşı bu jesti konuşuyor."},
            {"text": "Müşterilerini kap", "effects": {"money": 25, "honor": -3}, "result": "Ticaret savaştır. Kazandın — ama çarşıda 'acımasız' lafı geziyor."},
        ],
    },
    {
        "id": "v2_gece_yarisi_kapi",
        "title": "Gece Yarısı Kapı",
        "description": "Gece yarısı kapın çalındı: kaçak bir aile — 'Bizi bu geceliğine saklar mısınız? Peşimizdeler.'",
        "icon": "🚪",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "İçeri al", "effects": {"honor": 7, "crime": 5, "fear": 3}, "result": "Sabaha karşı yola çıktılar. Kim oldukların hiç öğrenemedin — ama o bakışı unutamazsın."},
            {"text": "Ahırda saklan de", "effects": {"honor": 3, "crime": 2}, "result": "Orta yol: yardım ettin ama eve sokmadın. Sabah iz bırakmadan gitmişlerdi."},
            {"text": "Kapıyı açma", "effects": {"fear": 1}, "result": "Ayak sesleri uzaklaştı. Ertesi gün tellal kaçakları okudu — ödül varmış. İyi mi yaptın kötü mü?"},
        ],
    },
    {
        "id": "v2_hamam_dedikodusu",
        "title": "Hamam Dedikodusu",
        "description": "Hamamda yan kurnada seni çekiştiriyorlar — adını duydun, kulağın delik.",
        "icon": "🛁",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Peştamalla ortaya çık: 'Devam edin?'", "effects": {"charisma": 1, "fear": 2, "reputation": 2}, "result": "Sessizlik... sonra kahkaha. Dedikoducular özür diledi; hamam destan oldu."},
            {"text": "Sessizce dinle, bilgi topla", "effects": {"intelligence": 1}, "result": "Kim dost kim düşman, artık biliyorsun. Bilgi hamam buharından sızar."},
            {"text": "Duymazdan gel", "effects": {}, "result": "Laf rüzgârdır dedin. Belki haklısın."},
        ],
    },
    {
        "id": "v2_eski_ask_mektubu",
        "title": "Eski Mektup",
        "description": "Sandığın dibinde gençlik aşkından kalma bir mektup buldun. Mürekkep solmuş, hatıralar solmamış.",
        "icon": "💌",
        "conditions": {"age_min": 35, "age_max": 60},
        "choices": [
            {"text": "Mektubu sakla", "effects": {"intelligence": 1}, "result": "Bazı şeyler sandıkta güzel durur. Kapağı usulca kapattın."},
            {"text": "Yak", "effects": {"honor": 2}, "result": "Alevler geçmişi aldı. Bugüne daha sıkı sarıldın."},
            {"text": "O kişiyi araştır: ne olmuş?", "effects": {"social": 1}, "result": "Komşu şehirde, torun sahibi olmuş. Gülümsedin: herkes kendi hikâyesini yaşamış."},
        ],
    },
    {
        "id": "v2_su_degirmeni",
        "title": "Değirmen Ortaklığı",
        "description": "Köy, dereye su değirmeni kurmak istiyor; ortak arıyorlar. Maliyet yüksek, getirisi uzun vadeli.",
        "icon": "🌀",
        "conditions": {"age_min": 30, "age_max": 55, "money_min": 60, "location_kind": "köy"},
        "choices": [
            {"text": "Büyük ortak ol", "effects": {"money": -60, "reputation": 5, "trade": 1}, "result": "Değirmen döndükçe payın gelecek. Köyün un derdi bitti, senin adın taşa kazındı."},
            {"text": "Küçük pay al", "effects": {"money": -25, "reputation": 2}, "result": "Riskin az, payın mütevazı. Dengeli iş."},
            {"text": "Katılma", "effects": {}, "result": "Değirmen sensiz kuruldu. Çark döndükçe için bir tuhaf oluyor."},
        ],
    },
    {
        "id": "v2_kuraklik_karari",
        "title": "Kuraklık Kararı",
        "description": "Yaz kurak geçti; ambarında fazla buğday var. Fiyatlar tavanda — köylü ise aç.",
        "icon": "🌾",
        "conditions": {"age_min": 30, "age_max": 60, "money_min": 50},
        "choices": [
            {"text": "Tavan fiyattan sat", "effects": {"money": 70, "reputation": -6, "honor": -4}, "result": "Kese doldu. Ama çocuklar sokakta arkandan 'vurguncu' diye bağırdı."},
            {"text": "Normal fiyattan köylüye sat", "effects": {"money": 30, "reputation": 6, "honor": 5}, "result": "Kıtlıkta insaf — köy bunu nesiller boyu anlatır."},
            {"text": "İhtiyacı olana dağıt", "effects": {"money": -10, "honor": 9, "reputation": 8}, "result": "Ambarın boşaldı, için doldu. Cuma vaazında adın geçti."},
        ],
    },
    {
        "id": "v2_oglun_meslegi",
        "title": "Evladın Yol Ayrımı",
        "description": "Çocuğun senin mesleğini istemiyor: 'Ben başka bir yol istiyorum' diyor. Gözlerinde korku ve umut.",
        "icon": "🛤️",
        "conditions": {"age_min": 35, "age_max": 60, "has_children": True},
        "choices": [
            {"text": "Destekle: 'Yolun açık olsun'", "effects": {"honor": 5, "money": -20}, "result": "Harçlığını verdin, sırtını sıvazladın. Giderken döndü: 'Sen dünyanın en iyi anası/babasısın.'"},
            {"text": "İkna et: 'Önce zanaatı öğren'", "effects": {"intelligence": 1, "crafting": 1}, "result": "Anlaştınız: iki yıl zanaat, sonra kendi yolu. İkiniz de kazandınız."},
            {"text": "Karşı çık: 'Bu ocak sönmez!'", "effects": {"reputation": -2, "honor": -3}, "result": "Kapıyı vurup çıktı. Aranızdaki soğukluk aylar sürdü."},
        ],
    },
    {
        "id": "v2_kadi_sahitligi",
        "title": "Mahkeme Şahitliği",
        "description": "Kadı seni şahit çağırdı: gördüğünü anlatırsan güçlü bir adam zarar görecek; susarsan masum yanacak.",
        "icon": "⚖️",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Doğruyu söyle", "effects": {"honor": 8, "reputation": 5, "fear": 4}, "result": "Sesin titredi ama sözün doğruydu. Masum kurtuldu; güçlü adam seni unutmayacak — iki anlamda da."},
            {"text": "'Görmedim' de", "effects": {"honor": -6, "money": 30}, "result": "Ertesi gün kapına bir kese bırakılmıştı. Kimden geldiğini ikiniz de biliyorsunuz."},
            {"text": "Şehirden uzaklaş, şahitlikten kaç", "effects": {"money": -15, "honor": -3}, "result": "Dava sensiz görüldü. Vicdanın hâlâ soruyor: ya sözün her şeyi değiştirecekse?"},
        ],
    },
    {
        "id": "v2_garip_hastalik",
        "title": "Uykusuzluk",
        "description": "Haftalardır doğru dürüst uyuyamıyorsun. Düşünceler gece çoğalıyor.",
        "icon": "🌙",
        "conditions": {"age_min": 35, "age_max": 60},
        "choices": [
            {"text": "Şifacıdan uyku otu al", "effects": {"money": -15, "health": 8}, "result": "Bitki çayı işe yaradı. Rüyalar geri geldi."},
            {"text": "Gece yürüyüşlerine başla", "effects": {"stamina": 1, "intelligence": 1}, "result": "Yıldızların altında zihin duruluyor. Uyku da yavaş yavaş döndü."},
            {"text": "Şarapla bastır", "effects": {"health": -8}, "result": "Uyudun ama dinlenmedin. Bu yol çıkmaz sokak."},
        ],
    },
    {
        "id": "v2_komsu_siniri",
        "title": "Çit Meselesi",
        "description": "Komşun çiti bir arşın senin tarafına kaydırmış. 'Eskiden de böyleydi' diyor.",
        "icon": "🚧",
        "conditions": {"age_min": 30, "age_max": 60},
        "choices": [
            {"text": "Muhtarla ölçtür", "effects": {"reputation": 3, "intelligence": 1}, "result": "İpler gerildi, ölçüldü: sen haklıydın. Çit yerine döndü, dostluk az hasarla kurtuldu."},
            {"text": "Gece çiti geri kaydır", "effects": {"crime": 3, "fear": 1}, "result": "Sabah komşu çiti gördü ve sustu. Sessiz bir savaş bu — kim bilir nereye varır."},
            {"text": "Bir arşını hediye et", "effects": {"honor": 4, "reputation": 2}, "result": "'Toprağın hayrını gör' dedin. Komşu utandı; ertesi hafta bahçenden eksik olmadı."},
        ],
    },

    # ═════════════════════════════════════════
    # 🧓 YAŞLILIK (50+) — 17 event
    # ═════════════════════════════════════════
    {
        "id": "v2_torun_dogumu",
        "title": "Torun Müjdesi",
        "description": "Haber geldi: torunun doğdu! Ev şenlik yeri.",
        "icon": "👶",
        "conditions": {"age_min": 50, "has_children": True},
        "choices": [
            {"text": "Büyük ziyafet ver", "effects": {"money": -30, "reputation": 5, "social": 1}, "result": "Sofralar kuruldu, dualar edildi. Adı yaşasın!"},
            {"text": "Torununa altın tak", "effects": {"money": -20, "honor": 3}, "result": "Minik bileğe ilk altını sen taktın. Gelenek yerini buldu."},
            {"text": "Sessizce şükret", "effects": {"honor": 2}, "result": "Pencereden gökyüzüne baktın. Hayat devam ediyor."},
        ],
    },
    {
        "id": "v2_eski_dusman_barismasi",
        "title": "Eski Düşman Kapıda",
        "description": "Yıllardır küs olduğun adam kapında, şapkası elinde: 'Ölmeden helalleşelim.'",
        "icon": "🕊️",
        "conditions": {"age_min": 50},
        "choices": [
            {"text": "Kucakla, helalleş", "effects": {"honor": 8, "reputation": 4}, "result": "İki ihtiyar kapı eşiğinde ağladı. Yıllar bir nefeste eridi."},
            {"text": "Konuş ama mesafeli", "effects": {"honor": 2}, "result": "Çay içildi, eski defterler yarım açıldı. Tam barış değil ama ateşkes."},
            {"text": "Kapıyı kapat", "effects": {"honor": -5}, "result": "Adam başını öne eğip gitti. Bir ay sonra cenazesini duydun."},
        ],
    },
    {
        "id": "v2_ani_yazma",
        "title": "Hatıralar",
        "description": "Torunun diz dibinde: 'Dede/nine, eskiden neler oldu? Anlatsana!'",
        "icon": "📜",
        "conditions": {"age_min": 55},
        "choices": [
            {"text": "Hayatını anlat, yazdır", "effects": {"intelligence": 1, "reputation": 4, "money": -10}, "result": "Katip üç akşam yazdı. Hikâyen artık kâğıtta — ölümsüz."},
            {"text": "Sadece güzel günleri anlat", "effects": {"charisma": 1}, "result": "Torunun gözleri yıldız gibi parladı. Bazı acılar sende kalsın."},
            {"text": "'Geçmiş geçmiştir' de", "effects": {}, "result": "Torun küstü ama akşam yine geldi: 'Peki ya o savaş?'"},
        ],
    },
    {
        "id": "v2_yasli_saglik",
        "title": "İhtiyarlık Sancısı",
        "description": "Dizler eskisi gibi değil; merdivenler dağ gibi. Şifacı 'yavaşla' diyor.",
        "icon": "🦯",
        "conditions": {"age_min": 55},
        "choices": [
            {"text": "Sözünü dinle, yavaşla", "effects": {"health": 10, "money": -10}, "result": "Bahçeye çekildin. Beden rahatladı; ruh da."},
            {"text": "İnat et, çalışmaya devam", "effects": {"health": -12, "stamina": 1, "honor": 2}, "result": "'Beni iş öldürmez, boş durmak öldürür!' Belki de haklısın."},
            {"text": "Baston yaptır, uyum sağla", "effects": {"money": -8, "health": 5, "charisma": 1}, "result": "Gümüş saplı bastonunla çarşıda bir efendi gibi yürüyorsun."},
        ],
    },
    {
        "id": "v2_mal_paylasimi_erken",
        "title": "Erken Paylaşım",
        "description": "Çocuklar mal paylaşımını şimdiden konuşuyor. Kulağına geldi; tatsızlık kokusu var.",
        "icon": "🏠",
        "conditions": {"age_min": 55, "has_children": True},
        "choices": [
            {"text": "Hepsini topla, açıkça konuş", "effects": {"reputation": 4, "honor": 5}, "result": "Sofrada her şey netleşti. Küslük çıkmadı — şimdilik."},
            {"text": "Vasiyeti gizlice yazdır", "effects": {"money": -15, "intelligence": 1}, "result": "Mühürlü zarf kadıda. Sürprizler ölümden sonraya."},
            {"text": "'Ben ölmeden konuşulmaz!'", "effects": {"fear": 3, "reputation": -2}, "result": "Sofra sessizliğe gömüldü. Konu kapandı ama fısıltılar sürüyor."},
        ],
    },
    {
        "id": "v2_genc_danisma",
        "title": "Gençlerin Akıl Danışması",
        "description": "Köyün gençleri kapında: büyük bir karar öncesi senin fikrini istiyorlar. 'Sen görmüş geçirmişsin.'",
        "icon": "🧙",
        "conditions": {"age_min": 55, "reputation_min": 10},
        "choices": [
            {"text": "Uzun uzun dinle, sonra konuş", "effects": {"reputation": 5, "intelligence": 1}, "result": "Sözlerin terazide tartılmış gibiydi. Gençler yol buldu; senin adın 'bilge'ye çıktı."},
            {"text": "Kendi gençlik hatanı anlat", "effects": {"honor": 4, "charisma": 1}, "result": "'Ben bu hatayı yaptım, siz yapmayın.' En değerli ders: yaşanmış olan."},
            {"text": "'Kendi yolunuzu bulun' de", "effects": {}, "result": "Gençler şaşırdı ama belki de en derin ders buydu."},
        ],
    },
    {
        "id": "v2_cesme_hayri",
        "title": "Hayır Çeşmesi",
        "description": "Para birikti, ömür azaldı. Köy meydanına bir çeşme yaptırmak — adını taşa kazımak — mümkün.",
        "icon": "⛲",
        "conditions": {"age_min": 55, "money_min": 100},
        "choices": [
            {"text": "Çeşmeyi yaptır", "effects": {"money": -100, "reputation": 10, "honor": 8}, "result": "Su akıyor, adın taşta: 'Bu çeşme bir hayırseverin eseridir.' Her yudum bir dua."},
            {"text": "Adsız yaptır", "effects": {"money": -100, "honor": 12}, "result": "Kimse bilmiyor. Sadece sen ve taş ustası. Belki de en saf hayır bu."},
            {"text": "Parayı çocuklara sakla", "effects": {}, "result": "Mirasa eklendi. Çeşme fikri kalbinde bir kuyu gibi kaldı."},
        ],
    },
    {
        "id": "v2_eski_zanaat",
        "title": "Unutulan Zanaat",
        "description": "Senin bildiğin eski bir tekniği artık kimse bilmiyor. Genç bir zanaatkâr öğrenmek için yalvarıyor.",
        "icon": "🛠️",
        "conditions": {"age_min": 55},
        "choices": [
            {"text": "Tüm sırları öğret", "effects": {"crafting": 1, "reputation": 6, "honor": 5}, "result": "Üç ay ders verdin. Zanaat ölmedi; senin ellerinden onunkilere geçti."},
            {"text": "Yarısını öğret, sırrını sakla", "effects": {"crafting": 1, "reputation": 2}, "result": "Temelleri verdin; ustalık sırrı seninle gidecek. Böylesi de bir gelenek."},
            {"text": "'Zanaat çile ister' diye reddet", "effects": {"reputation": -3}, "result": "Genç gitti. Gece düşündün: o teknik seninle toprağa mı girecek?"},
        ],
    },
    {
        "id": "v2_mezarlik_ziyareti",
        "title": "Mezarlık Ziyareti",
        "description": "Bahar temizliğinde aile mezarlığına gittin. Tanıdık isimler çoğalmış; yabani otlar da.",
        "icon": "🪦",
        "conditions": {"age_min": 50},
        "choices": [
            {"text": "Mezarları elinle temizle", "effects": {"honor": 5, "health": -5}, "result": "Taşları sildin, otları yoldun, duaları okudun. İçin hafifledi."},
            {"text": "Bakıcı tut", "effects": {"money": -15, "honor": 2}, "result": "Mezarlık düzenli artık. Atalar rahat uyusun."},
            {"text": "Kendi yerini de seç", "effects": {"intelligence": 1, "honor": 3}, "result": "Çınarın gölgesinde bir köşe. Garip bir huzur: her şey yerli yerinde."},
        ],
    },
    {
        "id": "v2_torun_egitimi",
        "title": "Torunun Eğitimi",
        "description": "Torunun zekâsı parlak ama ailesi okutmaya gücü yetmiyor. Dede/nine devreye girer mi?",
        "icon": "🎓",
        "conditions": {"age_min": 55, "has_children": True, "money_min": 40},
        "choices": [
            {"text": "Eğitim masrafını üstlen", "effects": {"money": -40, "honor": 6, "reputation": 3}, "result": "Torun mektebe başladı. Belki bir gün kadı olur, belki hekim — senin sayende."},
            {"text": "Kendin öğret", "effects": {"intelligence": 1, "honor": 4}, "result": "Her akşam diz dibinde ders. İki kuşak arasında köprü kuruldu."},
            {"text": "'Hayat okulu yeter' de", "effects": {}, "result": "Torun tarlaya gitti. Gözlerindeki soru hep aklında: 'ya okusaydı?'"},
        ],
    },
    {
        "id": "v2_yasli_dusme",
        "title": "Talihsiz Düşüş",
        "description": "Merdivenden düştün. Kalça ağrıyor; herkes telaşta.",
        "icon": "🤕",
        "conditions": {"age_min": 60},
        "choices": [
            {"text": "Şifacı + tam istirahat", "effects": {"money": -25, "health": -5}, "result": "Altı hafta yattın ama doğru kaynadı. Yine ayaktasın — daha dikkatli."},
            {"text": "'Bir şeyim yok' de, kalk", "effects": {"health": -20}, "result": "İnat ettin; kalça yamuk kaynadı. Artık her adım hatırlatıyor."},
        ],
    },
    {
        "id": "v2_eski_kral_aninda",
        "title": "Geçmişin Tanığı",
        "description": "Meydanda gençler eski kralın devrini tartışıyor — yanlış anlatıyorlar. Sen oradaydın.",
        "icon": "👑",
        "conditions": {"age_min": 60},
        "choices": [
            {"text": "Araya gir, doğrusunu anlat", "effects": {"reputation": 4, "charisma": 1}, "result": "Meydan sustu, kulak kesildi. Canlı tarih konuşunca kitaplar kapanır."},
            {"text": "Gülümseyip geç", "effects": {"intelligence": 1}, "result": "Her kuşak tarihi yeniden yazar. Bırak yazsınlar."},
        ],
    },
    {
        "id": "v2_kis_hazirligi",
        "title": "Zorlu Kış Habercisi",
        "description": "Karıncalar yüksek tepeler yapıyor, kuşlar erken göçtü. Sen bu işaretleri bilirsin: kış sert geçecek.",
        "icon": "❄️",
        "conditions": {"age_min": 50},
        "choices": [
            {"text": "Köyü uyar, hazırlık başlat", "effects": {"reputation": 5, "intelligence": 1}, "result": "Ambarlar dolduruldu, odunlar kesildi. Kış geldiğinde köy hazırdı — senin sayende."},
            {"text": "Sadece kendi kışlığını topla", "effects": {"money": -15}, "result": "Senin kileri dolu. Kış bastırınca komşular kapına geldi..."},
            {"text": "'Belki yanılıyorumdur'", "effects": {}, "result": "Yanılmıyordun. Kış acımasız geldi; keşke konuşsaydın."},
        ],
    },
    {
        "id": "v2_imamlik_teklifi",
        "title": "Cemaat Önderliği",
        "description": "Mahalle senin dindarlığına ve dürüstlüğüne güveniyor: cemaate önderlik etmen isteniyor.",
        "icon": "🕌",
        "conditions": {"age_min": 55, "reputation_min": 20},
        "choices": [
            {"text": "Kabul et", "effects": {"reputation": 6, "honor": 5}, "result": "Önde durmak yük ama şereftir. Sözün artık mahallede terazi."},
            {"text": "Daha ehlini öner", "effects": {"honor": 4, "reputation": 2}, "result": "Tevazun takdir gördü. Önerdiğin kişi her hutbede sana dua ediyor."},
        ],
    },
    {
        "id": "v2_son_yolculuk_plani",
        "title": "Hac Yolu Hayali",
        "description": "Ömürlük hayalin: kutsal topraklara yolculuk. Beden yaşlı, yol uzun, kese orta halli.",
        "icon": "🕋",
        "conditions": {"age_min": 55, "money_min": 80},
        "choices": [
            {"text": "Yola çık", "effects": {"money": -80, "health": -15, "honor": 10, "fame": 5}, "result": "Aylar süren yol... Döndüğünde bambaşka biriydin. Herkes elini öpmeye geliyor."},
            {"text": "Vekil gönder", "effects": {"money": -40, "honor": 4}, "result": "Genç bir komşu senin adına gitti. Sevabı bölüştünüz."},
            {"text": "Ertele", "effects": {}, "result": "'Bir dahaki bahara...' Ömrün baharı kaç kere döner ki?"},
        ],
    },
    {
        "id": "v2_yasli_bilgelik_satisi",
        "title": "Tüccarın Sorusu",
        "description": "Genç bir tüccar yanına oturdu: 'Bana tek bir öğüt ver, ne istersen ödeyeyim.'",
        "icon": "💬",
        "conditions": {"age_min": 60},
        "choices": [
            {"text": "'Adını altından kıymetli tut' de, para alma", "effects": {"honor": 6, "reputation": 4}, "result": "Tüccar uzun süre sustu. Yıllar sonra şehrin en namuslu tüccarı diye onun adı anılıyordu."},
            {"text": "Öğüdü ver, parayı al", "effects": {"money": 30, "honor": -1}, "result": "Bilgelik de bir maldır. Tüccar memnun, sen de."},
            {"text": "'Öğüt satılmaz, yaşanır' de", "effects": {"intelligence": 1, "honor": 3}, "result": "Tüccar güldü: 'İşte bu, en pahalı öğüttü.' Kalktı, saygıyla eğildi."},
        ],
    },
    {
        "id": "v2_yildonumu",
        "title": "Evlilik Yıldönümü",
        "description": "Eşinle nice yılı devirdiniz. Bugün o gün — hatırlayan var mı?",
        "icon": "💑",
        "conditions": {"age_min": 50, "has_spouse": True},
        "choices": [
            {"text": "Sürpriz hazırla", "effects": {"money": -20, "charisma": 1, "honor": 3}, "result": "Eşinin yüzündeki şaşkınlık ve gülümseme... Yıllar bir anda gençleşti."},
            {"text": "Birlikte eski yerlere yürüyün", "effects": {"health": 5, "honor": 2}, "result": "İlk karşılaştığınız çeşme hâlâ akıyor. Siz de hâlâ el eleydiniz."},
            {"text": "Unutmuş gibi yap, akşam hediye ver", "effects": {"charisma": 1}, "result": "Bütün gün süzgün dolaştı; akşam hediyeyi görünce 'Seni yaşlı kurnaz!' diye güldü."},
        ],
    },
]
