"""12 Hikâye Yayı — GDD v5 Faz 2B (lansman seti).

Saf veri: motor quest_engine.py, metinler locales/tr_arcs.py.
Her seçenek ya doğrudan dal ("sonraki", "efekt", "sonuc_key") ya da
testli daldır ("test" + "basari"/"basarisizlik").
"sonraki": None → yay biter; "bitis" alanı yoksa "tamamlandı" sayılır.
"""

STORY_ARCS = [
    # ══ 1. KÜLLERİN SIRRI — ana yay ═══════════════════════════════════════
    {
        "id": "kullerin_sirri",
        "baslik_key": "yay.kul.baslik",
        "kanca_key": "yay.kul.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 10, "bayrak_yok": ["kül_tamam", "kül_kayip"]},
        "zaman_siniri_hafta": None,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.kul.a1", "secenekler": [
                {"metin_key": "yay.kul.a1.s0", "sonraki": "a2",
                 "efekt": {"stat_xp": {"intelligence": 3}}, "sonuc_key": "yay.kul.a1.s0.ok"},
                {"metin_key": "yay.kul.a1.s1", "sonraki": "a2",
                 "efekt": {"bayrak": {"kül_gizli": True}}, "sonuc_key": "yay.kul.a1.s1.ok"},
                {"metin_key": "yay.kul.a1.s2", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"para": 60, "onur": -5, "bayrak": {"kül_kayip": True}},
                 "sonuc_key": "yay.kul.a1.s2.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.kul.a2", "secenekler": [
                {"metin_key": "yay.kul.a2.s0", "sonraki": "a3", "sonuc_key": "yay.kul.a2.s0.ok"},
                {"metin_key": "yay.kul.a2.s1", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"bayrak": {"kül_kayip": True}}, "sonuc_key": "yay.kul.a2.s1.ok"},
            ]},
            {"id": "a3", "metin_key": "yay.kul.a3", "secenekler": [
                {"metin_key": "yay.kul.a3.s0", "test": {"stat": {"charisma": 4}},
                 "basari": {"sonraki": "a4", "efekt": {"itibar": 2}, "sonuc_key": "yay.kul.a3.s0.ok"},
                 "basarisizlik": {"sonraki": "a3b", "bekle_hafta": 2, "sonuc_key": "yay.kul.a3.s0.fail"}},
                {"metin_key": "yay.kul.a3.s1", "sonraki": "a3b", "bekle_hafta": 1,
                 "sonuc_key": "yay.kul.a3.s1.ok"},
            ]},
            {"id": "a3b", "metin_key": "yay.kul.a3b", "secenekler": [
                {"metin_key": "yay.kul.a3b.s0", "test": {"skill": {"crafting": 2}},
                 "basari": {"sonraki": "a4", "efekt": {"suc": 10}, "sonuc_key": "yay.kul.a3b.s0.ok"},
                 "basarisizlik": {"sonraki": "a4", "efekt": {"suc": 20, "para": -40, "saglik": -5},
                                  "sonuc_key": "yay.kul.a3b.s0.fail"}},
                {"metin_key": "yay.kul.a3b.s1", "sonraki": "a4", "bekle_hafta": 3,
                 "efekt": {"para": -80}, "sonuc_key": "yay.kul.a3b.s1.ok"},
            ]},
            {"id": "a4", "metin_key": "yay.kul.a4", "secenekler": [
                {"metin_key": "yay.kul.a4.s0", "sonraki": "a5", "bekle_hafta": 3,
                 "sonuc_key": "yay.kul.a4.s0.ok"},
            ]},
            {"id": "a5", "metin_key": "yay.kul.a5", "secenekler": [
                {"metin_key": "yay.kul.a5.s0", "test": {"skill": {"combat": 3}},
                 "basari": {"sonraki": "a6", "efekt": {"un": 10, "korku": 8, "bayrak": {"kül_yol": "intikam"}},
                            "sonuc_key": "yay.kul.a5.s0.ok"},
                 "basarisizlik": {"sonraki": "a6", "efekt": {"saglik": -25, "bayrak": {"kül_yol": "yenilgi"}},
                                  "sonuc_key": "yay.kul.a5.s0.fail"}},
                {"metin_key": "yay.kul.a5.s1", "test": {"stat": {"intelligence": 5}},
                 "basari": {"sonraki": "a6", "efekt": {"itibar": 12, "bayrak": {"kül_yol": "adalet"}},
                            "sonuc_key": "yay.kul.a5.s1.ok"},
                 "basarisizlik": {"sonraki": "a6", "efekt": {"itibar": -5, "bayrak": {"kül_yol": "adalet_yarim"}},
                                  "sonuc_key": "yay.kul.a5.s1.fail"}},
                {"metin_key": "yay.kul.a5.s2", "sonraki": "a6",
                 "efekt": {"onur": 10, "bayrak": {"kül_yol": "af"}}, "sonuc_key": "yay.kul.a5.s2.ok"},
            ]},
            {"id": "a6", "metin_key": "yay.kul.a6", "secenekler": [
                {"metin_key": "yay.kul.a6.s0", "sonraki": None,
                 "efekt": {"bayrak": {"kül_tamam": True}}, "sonuc_key": "yay.kul.a6.s0.ok"},
            ]},
        ],
        "odul": {"para": 200, "itibar": 8, "esya": {"mücevher": 1},
                 "stat_xp": {"intelligence": 10}},
    },

    # ══ 2. GİZLİ CEMİYET'İN DAVETİ ════════════════════════════════════════
    {
        "id": "gizli_cemiyet",
        "baslik_key": "yay.cemiyet.baslik",
        "kanca_key": "yay.cemiyet.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 18, "itibar_min": 20},
        "zaman_siniri_hafta": 12,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.cemiyet.a1", "secenekler": [
                {"metin_key": "yay.cemiyet.a1.s0", "sonraki": "a2", "sonuc_key": "yay.cemiyet.a1.s0.ok"},
                {"metin_key": "yay.cemiyet.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "sonuc_key": "yay.cemiyet.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.cemiyet.a2", "secenekler": [
                {"metin_key": "yay.cemiyet.a2.s0", "test": {"stat": {"intelligence": 5}},
                 "basari": {"sonraki": "a3", "efekt": {"skill_xp": {"social": 8}},
                            "sonuc_key": "yay.cemiyet.a2.s0.ok"},
                 "basarisizlik": {"sonraki": "a3", "efekt": {"suc": 8, "saglik": -10},
                                  "sonuc_key": "yay.cemiyet.a2.s0.fail"}},
            ]},
            {"id": "a3", "metin_key": "yay.cemiyet.a3", "secenekler": [
                {"metin_key": "yay.cemiyet.a3.s0", "sonraki": None,
                 "efekt": {"bayrak": {"cemiyet_üye": True}, "korku": 5},
                 "sonuc_key": "yay.cemiyet.a3.s0.ok"},
                {"metin_key": "yay.cemiyet.a3.s1", "sonraki": None,
                 "efekt": {"bayrak": {"cemiyet_dusman": True}, "itibar": 10},
                 "sonuc_key": "yay.cemiyet.a3.s1.ok"},
            ]},
        ],
        "odul": {"para": 150, "skill_xp": {"social": 10}},
    },

    # ══ 3. VEBANIN GÖLGESİ ════════════════════════════════════════════════
    {
        "id": "vebanin_golgesi",
        "baslik_key": "yay.veba.baslik",
        "kanca_key": "yay.veba.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 13},
        "zaman_siniri_hafta": 10,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.veba.a1", "secenekler": [
                {"metin_key": "yay.veba.a1.s0", "sonraki": "a2", "sonuc_key": "yay.veba.a1.s0.ok"},
                {"metin_key": "yay.veba.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"itibar": -8, "bayrak": {"veba_kacti": True}},
                 "sonuc_key": "yay.veba.a1.s1.ok"},
                {"metin_key": "yay.veba.a1.s2", "test": {"stat": {"charisma": 4}},
                 "basari": {"sonraki": "a3", "sonuc_key": "yay.veba.a1.s2.ok"},
                 "basarisizlik": {"sonraki": "a2", "efekt": {"itibar": -3},
                                  "sonuc_key": "yay.veba.a1.s2.fail"}},
            ]},
            {"id": "a2", "metin_key": "yay.veba.a2", "secenekler": [
                {"metin_key": "yay.veba.a2.s0", "test": {"stat": {"intelligence": 4}},
                 "basari": {"sonraki": None, "efekt": {"itibar": 10, "esya": {"şifalı_ot": 3}},
                            "sonuc_key": "yay.veba.a2.s0.ok"},
                 "basarisizlik": {"sonraki": "a2b", "efekt": {"saglik": -20},
                                  "sonuc_key": "yay.veba.a2.s0.fail"}},
            ]},
            {"id": "a2b", "metin_key": "yay.veba.a2b", "secenekler": [
                {"metin_key": "yay.veba.a2b.s0", "sonraki": None, "bekle_hafta": 2,
                 "efekt": {"saglik": 10}, "sonuc_key": "yay.veba.a2b.s0.ok"},
            ]},
            {"id": "a3", "metin_key": "yay.veba.a3", "secenekler": [
                {"metin_key": "yay.veba.a3.s0", "test": {"stat": {"charisma": 5}},
                 "basari": {"sonraki": None, "efekt": {"itibar": 15, "un": 8, "bayrak": {"veba_kahraman": True}},
                            "sonuc_key": "yay.veba.a3.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"itibar": -10}, "sonuc_key": "yay.veba.a3.s0.fail"}},
            ]},
        ],
        "odul": {"para": 120, "skill_xp": {"social": 6}, "stat_xp": {"intelligence": 6}},
    },

    # ══ 4. TAHTIN GÖLGESİNDE ══════════════════════════════════════════════
    {
        "id": "tahtin_golgesinde",
        "baslik_key": "yay.taht.baslik",
        "kanca_key": "yay.taht.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 20, "itibar_min": 30, "lokasyon_tipi": "şehir"},
        "zaman_siniri_hafta": 16,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.taht.a1", "secenekler": [
                {"metin_key": "yay.taht.a1.s0", "sonraki": "a2", "sonuc_key": "yay.taht.a1.s0.ok"},
                {"metin_key": "yay.taht.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "sonuc_key": "yay.taht.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.taht.a2", "secenekler": [
                {"metin_key": "yay.taht.a2.s0", "sonraki": "a3",
                 "efekt": {"bayrak": {"taht_taraf": "veliaht"}}, "sonuc_key": "yay.taht.a2.s0.ok"},
                {"metin_key": "yay.taht.a2.s1", "sonraki": "a3",
                 "efekt": {"bayrak": {"taht_taraf": "kral"}}, "sonuc_key": "yay.taht.a2.s1.ok"},
            ]},
            {"id": "a3", "metin_key": "yay.taht.a3", "secenekler": [
                {"metin_key": "yay.taht.a3.s0", "test": {"stat": {"intelligence": 6}},
                 "basari": {"sonraki": "a4", "bekle_hafta": 2, "efekt": {"para": 100},
                            "sonuc_key": "yay.taht.a3.s0.ok"},
                 "basarisizlik": {"sonraki": "a4", "bekle_hafta": 2,
                                  "efekt": {"suc": 15, "korku": 5}, "sonuc_key": "yay.taht.a3.s0.fail"}},
                {"metin_key": "yay.taht.a3.s1", "test": {"skill": {"social": 4}},
                 "basari": {"sonraki": "a4", "bekle_hafta": 2, "efekt": {"itibar": 5},
                            "sonuc_key": "yay.taht.a3.s1.ok"},
                 "basarisizlik": {"sonraki": "a4", "bekle_hafta": 2, "efekt": {"itibar": -5},
                                  "sonuc_key": "yay.taht.a3.s1.fail"}},
            ]},
            {"id": "a4", "metin_key": "yay.taht.a4", "secenekler": [
                {"metin_key": "yay.taht.a4.s0", "test": {"stat": {"charisma": 6}},
                 "basari": {"sonraki": None, "efekt": {"para": 400, "itibar": 15, "un": 15,
                                                       "bayrak": {"taht_sonuc": "zafer"}},
                            "sonuc_key": "yay.taht.a4.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"itibar": -15, "suc": 20, "bayrak": {"taht_sonuc": "sürgün"}},
                                  "sonuc_key": "yay.taht.a4.s0.fail"}},
                {"metin_key": "yay.taht.a4.s1", "sonraki": None,
                 "efekt": {"para": 80, "bayrak": {"taht_sonuc": "çekilme"}},
                 "sonuc_key": "yay.taht.a4.s1.ok"},
            ]},
        ],
        "odul": {"para": 250, "itibar": 10, "skill_xp": {"social": 12}},
    },

    # ══ 5. KANLI MİRAS ════════════════════════════════════════════════════
    {
        "id": "kanli_miras",
        "baslik_key": "yay.kan.baslik",
        "kanca_key": "yay.kan.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 16},
        "zaman_siniri_hafta": 10,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.kan.a1", "secenekler": [
                {"metin_key": "yay.kan.a1.s0", "sonraki": "a2",
                 "efekt": {"stat_xp": {"intelligence": 4}}, "sonuc_key": "yay.kan.a1.s0.ok"},
                {"metin_key": "yay.kan.a1.s1", "sonraki": "a2", "efekt": {"para": -100},
                 "sonuc_key": "yay.kan.a1.s1.ok"},
                {"metin_key": "yay.kan.a1.s2", "sonraki": "a2b", "bekle_hafta": 2,
                 "sonuc_key": "yay.kan.a1.s2.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.kan.a2", "secenekler": [
                {"metin_key": "yay.kan.a2.s0", "test": {"skill": {"combat": 3}},
                 "basari": {"sonraki": "a3", "efekt": {"un": 5}, "sonuc_key": "yay.kan.a2.s0.ok"},
                 "basarisizlik": {"sonraki": "a3", "efekt": {"saglik": -20},
                                  "sonuc_key": "yay.kan.a2.s0.fail"}},
            ]},
            {"id": "a2b", "metin_key": "yay.kan.a2b", "secenekler": [
                {"metin_key": "yay.kan.a2b.s0", "sonraki": "a3", "efekt": {"saglik": -15},
                 "sonuc_key": "yay.kan.a2b.s0.ok"},
            ]},
            {"id": "a3", "metin_key": "yay.kan.a3", "secenekler": [
                {"metin_key": "yay.kan.a3.s0", "test": {"skill": {"combat": 4}},
                 "basari": {"sonraki": None, "efekt": {"suc": 30, "korku": 12, "un": 8,
                                                       "bayrak": {"kan_sonuc": "intikam"}},
                            "sonuc_key": "yay.kan.a3.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"saglik": -35}, "sonuc_key": "yay.kan.a3.s0.fail"}},
                {"metin_key": "yay.kan.a3.s1", "test": {"stat": {"charisma": 5}},
                 "basari": {"sonraki": None, "efekt": {"onur": 10, "itibar": 8,
                                                       "bayrak": {"kan_sonuc": "barış"}},
                            "sonuc_key": "yay.kan.a3.s1.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"saglik": -20}, "sonuc_key": "yay.kan.a3.s1.fail"}},
                {"metin_key": "yay.kan.a3.s2", "sonraki": None,
                 "efekt": {"itibar": 5, "bayrak": {"kan_sonuc": "adalet"}},
                 "sonuc_key": "yay.kan.a3.s2.ok"},
            ]},
        ],
        "odul": {"para": 180, "skill_xp": {"combat": 10}},
    },

    # ══ 6. İPEK YOLU RÜYASI ═══════════════════════════════════════════════
    {
        "id": "ipek_yolu",
        "baslik_key": "yay.ipek.baslik",
        "kanca_key": "yay.ipek.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 18, "skill": {"trade": 3}, "mulk_min": 1},
        "zaman_siniri_hafta": 14,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.ipek.a1", "secenekler": [
                {"metin_key": "yay.ipek.a1.s0", "sonraki": "a2", "efekt": {"para": -300},
                 "sonuc_key": "yay.ipek.a1.s0.ok"},
                {"metin_key": "yay.ipek.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "sonuc_key": "yay.ipek.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.ipek.a2", "secenekler": [
                {"metin_key": "yay.ipek.a2.s0", "sonraki": "a3", "bekle_hafta": 4,
                 "efekt": {"bayrak": {"ipek_rota": "güvenli"}}, "sonuc_key": "yay.ipek.a2.s0.ok"},
                {"metin_key": "yay.ipek.a2.s1", "test": {"skill": {"trade": 4}},
                 "basari": {"sonraki": "a3", "bekle_hafta": 4,
                            "efekt": {"bayrak": {"ipek_rota": "riskli_ok"}},
                            "sonuc_key": "yay.ipek.a2.s1.ok"},
                 "basarisizlik": {"sonraki": "a3", "bekle_hafta": 4,
                                  "efekt": {"bayrak": {"ipek_rota": "riskli_fail"}, "para": -100},
                                  "sonuc_key": "yay.ipek.a2.s1.fail"}},
            ]},
            {"id": "a3", "metin_key": "yay.ipek.a3", "secenekler": [
                {"metin_key": "yay.ipek.a3.s0", "sonraki": None,
                 "efekt": {"esya": {"ipek": 5, "baharat": 5}, "bayrak": {"ipek_baron": True}},
                 "sonuc_key": "yay.ipek.a3.s0.ok"},
            ]},
        ],
        "odul": {"para": 700, "skill_xp": {"trade": 15}, "un": 10},
    },

    # ══ 7. YASAK AŞK ══════════════════════════════════════════════════════
    {
        "id": "yasak_ask",
        "baslik_key": "yay.ask.baslik",
        "kanca_key": "yay.ask.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 16, "es_yok": True},
        "zaman_siniri_hafta": 12,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.ask.a1", "secenekler": [
                {"metin_key": "yay.ask.a1.s0", "sonraki": "a2", "bekle_hafta": 2,
                 "sonuc_key": "yay.ask.a1.s0.ok"},
                {"metin_key": "yay.ask.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"onur": 2}, "sonuc_key": "yay.ask.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.ask.a2", "secenekler": [
                {"metin_key": "yay.ask.a2.s0", "sonraki": "a3", "sonuc_key": "yay.ask.a2.s0.ok"},
                {"metin_key": "yay.ask.a2.s1", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"saglik": -5}, "sonuc_key": "yay.ask.a2.s1.ok"},
            ]},
            {"id": "a3", "metin_key": "yay.ask.a3", "secenekler": [
                {"metin_key": "yay.ask.a3.s0", "sonraki": None,
                 "efekt": {"itibar": -15, "onur": -5, "bayrak": {"ask_sonuc": "kaçış"}},
                 "sonuc_key": "yay.ask.a3.s0.ok"},
                {"metin_key": "yay.ask.a3.s1", "test": {"stat": {"charisma": 6}},
                 "basari": {"sonraki": None, "efekt": {"itibar": 10, "bayrak": {"ask_sonuc": "kabul"}},
                            "sonuc_key": "yay.ask.a3.s1.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"itibar": -5, "bayrak": {"ask_sonuc": "ret"}},
                                  "sonuc_key": "yay.ask.a3.s1.fail"}},
                {"metin_key": "yay.ask.a3.s2", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"onur": 3, "bayrak": {"ask_sonuc": "vazgeçti"}},
                 "sonuc_key": "yay.ask.a3.s2.ok"},
            ]},
        ],
        "odul": {"stat_xp": {"charisma": 12}, "skill_xp": {"social": 8}},
    },

    # ══ 8. HOCANIN MİRASI ═════════════════════════════════════════════════
    {
        "id": "hocanin_mirasi",
        "baslik_key": "yay.hoca.baslik",
        "kanca_key": "yay.hoca.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 10, "yas_max": 17},
        "zaman_siniri_hafta": 8,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.hoca.a1", "secenekler": [
                {"metin_key": "yay.hoca.a1.s0", "sonraki": "a2", "sonuc_key": "yay.hoca.a1.s0.ok"},
                {"metin_key": "yay.hoca.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "sonuc_key": "yay.hoca.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.hoca.a2", "secenekler": [
                {"metin_key": "yay.hoca.a2.s0", "test": {"stat": {"intelligence": 3}},
                 "basari": {"sonraki": "a3", "efekt": {"stat_xp": {"intelligence": 6}},
                            "sonuc_key": "yay.hoca.a2.s0.ok"},
                 "basarisizlik": {"sonraki": "a2", "bekle_hafta": 1,
                                  "sonuc_key": "yay.hoca.a2.s0.fail"}},
            ]},
            {"id": "a3", "metin_key": "yay.hoca.a3", "secenekler": [
                {"metin_key": "yay.hoca.a3.s0", "sonraki": None,
                 "efekt": {"stat_xp": {"intelligence": 15}, "bayrak": {"hoca_kitap": "ilim"}},
                 "sonuc_key": "yay.hoca.a3.s0.ok"},
                {"metin_key": "yay.hoca.a3.s1", "sonraki": None,
                 "efekt": {"skill_xp": {"trade": 15}, "bayrak": {"hoca_kitap": "hesap"}},
                 "sonuc_key": "yay.hoca.a3.s1.ok"},
                {"metin_key": "yay.hoca.a3.s2", "sonraki": None,
                 "efekt": {"skill_xp": {"combat": 15}, "bayrak": {"hoca_kitap": "strateji"}},
                 "sonuc_key": "yay.hoca.a3.s2.ok"},
            ]},
        ],
        "odul": {"itibar": 5},
    },

    # ══ 9. HAYDUT KRALI ═══════════════════════════════════════════════════
    {
        "id": "haydut_krali",
        "baslik_key": "yay.haydut.baslik",
        "kanca_key": "yay.haydut.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 18, "suc_min": 30},
        "zaman_siniri_hafta": 12,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.haydut.a1", "secenekler": [
                {"metin_key": "yay.haydut.a1.s0", "sonraki": "a2", "sonuc_key": "yay.haydut.a1.s0.ok"},
                {"metin_key": "yay.haydut.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"itibar": 5, "suc": -10}, "sonuc_key": "yay.haydut.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.haydut.a2", "secenekler": [
                {"metin_key": "yay.haydut.a2.s0", "test": {"skill": {"combat": 4}, "stat": {"intelligence": 4}},
                 "basari": {"sonraki": "a3", "efekt": {"para": 350, "suc": 25, "un": 10},
                            "sonuc_key": "yay.haydut.a2.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"suc": 40, "saglik": -25, "para": -100},
                                  "sonuc_key": "yay.haydut.a2.s0.fail"}},
            ]},
            {"id": "a3", "metin_key": "yay.haydut.a3", "secenekler": [
                {"metin_key": "yay.haydut.a3.s0", "test": {"skill": {"combat": 5}},
                 "basari": {"sonraki": None, "efekt": {"korku": 25, "un": 20, "suc": 20,
                                                       "bayrak": {"haydut_kral": True}},
                            "sonuc_key": "yay.haydut.a3.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"saglik": -40}, "sonuc_key": "yay.haydut.a3.s0.fail"}},
                {"metin_key": "yay.haydut.a3.s1", "sonraki": None,
                 "efekt": {"para": 200, "bayrak": {"haydut_kral": False}},
                 "sonuc_key": "yay.haydut.a3.s1.ok"},
            ]},
        ],
        "odul": {"para": 300, "skill_xp": {"combat": 12}},
    },

    # ══ 10. ADALET TERAZİSİ ═══════════════════════════════════════════════
    {
        "id": "adalet_terazisi",
        "baslik_key": "yay.adalet.baslik",
        "kanca_key": "yay.adalet.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 16},
        "zaman_siniri_hafta": 8,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.adalet.a1", "secenekler": [
                {"metin_key": "yay.adalet.a1.s0", "test": {"stat": {"intelligence": 4}},
                 "basari": {"sonraki": "a2", "sonuc_key": "yay.adalet.a1.s0.ok"},
                 "basarisizlik": {"sonraki": "a2", "efekt": {"itibar": -8},
                                  "sonuc_key": "yay.adalet.a1.s0.fail"}},
                {"metin_key": "yay.adalet.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"suc": 25, "korku": 5, "bayrak": {"adalet_sonuc": "firar"}},
                 "sonuc_key": "yay.adalet.a1.s1.ok"},
                {"metin_key": "yay.adalet.a1.s2", "sonraki": None, "bitis": "başarısız",
                 "efekt": {"para": -150, "itibar": -10, "bayrak": {"adalet_sonuc": "boyun_eğdi"}},
                 "sonuc_key": "yay.adalet.a1.s2.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.adalet.a2", "secenekler": [
                {"metin_key": "yay.adalet.a2.s0", "test": {"stat": {"intelligence": 5}},
                 "basari": {"sonraki": None, "efekt": {"itibar": 15, "onur": 8,
                                                       "bayrak": {"adalet_sonuc": "aklandı"}},
                            "sonuc_key": "yay.adalet.a2.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"para": -200, "itibar": -12,
                                            "bayrak": {"adalet_sonuc": "mahkum"}},
                                  "sonuc_key": "yay.adalet.a2.s0.fail"}},
            ], },
        ],
        "odul": {"para": 100, "itibar": 5, "stat_xp": {"intelligence": 8}},
    },

    # ══ 11. TOPRAK DAVASI ═════════════════════════════════════════════════
    {
        "id": "toprak_davasi",
        "baslik_key": "yay.toprak.baslik",
        "kanca_key": "yay.toprak.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 20, "lokasyon_tipi": "köy"},
        "zaman_siniri_hafta": 10,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.toprak.a1", "secenekler": [
                {"metin_key": "yay.toprak.a1.s0", "sonraki": "a2", "bekle_hafta": 2,
                 "sonuc_key": "yay.toprak.a1.s0.ok"},
                {"metin_key": "yay.toprak.a1.s1", "test": {"stat": {"charisma": 5}},
                 "basari": {"sonraki": None, "efekt": {"itibar": 12, "onur": 5,
                                                       "bayrak": {"toprak_sonuc": "uzlaşma"}},
                            "sonuc_key": "yay.toprak.a1.s1.ok"},
                 "basarisizlik": {"sonraki": "a2", "efekt": {"itibar": -3},
                                  "sonuc_key": "yay.toprak.a1.s1.fail"}},
                {"metin_key": "yay.toprak.a1.s2", "test": {"skill": {"combat": 3}},
                 "basari": {"sonraki": None, "efekt": {"suc": 20, "korku": 10,
                                                       "bayrak": {"toprak_sonuc": "zorbalık"}},
                            "sonuc_key": "yay.toprak.a1.s2.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"saglik": -20, "itibar": -8},
                                  "sonuc_key": "yay.toprak.a1.s2.fail"}},
            ]},
            {"id": "a2", "metin_key": "yay.toprak.a2", "secenekler": [
                {"metin_key": "yay.toprak.a2.s0", "test": {"stat": {"intelligence": 4}},
                 "basari": {"sonraki": None, "efekt": {"itibar": 10, "para": 80,
                                                       "bayrak": {"toprak_sonuc": "dava_kazanıldı"}},
                            "sonuc_key": "yay.toprak.a2.s0.ok"},
                 "basarisizlik": {"sonraki": None, "bitis": "başarısız",
                                  "efekt": {"para": -100, "bayrak": {"toprak_sonuc": "dava_kaybedildi"}},
                                  "sonuc_key": "yay.toprak.a2.s0.fail"}},
            ]},
        ],
        "odul": {"itibar": 8, "skill_xp": {"social": 8}},
    },

    # ══ 12. SON VASİYET ═══════════════════════════════════════════════════
    {
        "id": "son_vasiyet",
        "baslik_key": "yay.vasiyet.baslik",
        "kanca_key": "yay.vasiyet.kanca",
        "tur": "zincir",
        "tetik": {"yas_min": 50},
        "zaman_siniri_hafta": None,
        "adimlar": [
            {"id": "a1", "metin_key": "yay.vasiyet.a1", "secenekler": [
                {"metin_key": "yay.vasiyet.a1.s0", "sonraki": "a2", "sonuc_key": "yay.vasiyet.a1.s0.ok"},
                {"metin_key": "yay.vasiyet.a1.s1", "sonraki": None, "bitis": "başarısız",
                 "sonuc_key": "yay.vasiyet.a1.s1.ok"},
            ]},
            {"id": "a2", "metin_key": "yay.vasiyet.a2", "secenekler": [
                {"metin_key": "yay.vasiyet.a2.s0", "sonraki": "a3",
                 "efekt": {"bayrak": {"vasiyet_stil": "eşit"}}, "sonuc_key": "yay.vasiyet.a2.s0.ok"},
                {"metin_key": "yay.vasiyet.a2.s1", "sonraki": "a3",
                 "efekt": {"bayrak": {"vasiyet_stil": "tek_varis"}}, "sonuc_key": "yay.vasiyet.a2.s1.ok"},
                {"metin_key": "yay.vasiyet.a2.s2", "sonraki": "a3",
                 "efekt": {"itibar": 12, "para": -200, "bayrak": {"vasiyet_stil": "hayır"}},
                 "sonuc_key": "yay.vasiyet.a2.s2.ok"},
            ]},
            {"id": "a3", "metin_key": "yay.vasiyet.a3", "secenekler": [
                {"metin_key": "yay.vasiyet.a3.s0", "sonraki": None, "bekle_hafta": 2,
                 "efekt": {"bayrak": {"vasiyet_tamam": True}, "onur": 8},
                 "sonuc_key": "yay.vasiyet.a3.s0.ok"},
            ]},
        ],
        "odul": {"itibar": 10, "stat_xp": {"intelligence": 5}},
    },
]
