# -*- coding: utf-8 -*-
"""
Bilgi destesi — kanalın içerik kaynağı. Oyundan ve dış API'lerden bağımsız.

Yeni video eklemek = listeye yeni kayıt eklemek. Şema:
  id        benzersiz kimlik (published.json takibi için)
  kategori  UZAY | HAYVANLAR | İNSAN VÜCUDU | TARİH | BİLİM | DÜNYA
  soru      kanca — videonun başlığı da bundan üretilir
  cevap     kısa, vurucu cevap (reveal ekranı)
  aciklama  1-2 cümlelik bağlam (detay ekranı)
"""

FACTS = [
    # ── UZAY ──────────────────────────────────────────
    {"id": "venus_gun", "kategori": "UZAY",
     "soru": "Venüs'te bir gün mü daha uzun, bir yıl mı?",
     "cevap": "Bir gün!",
     "aciklama": "Venüs kendi etrafında o kadar yavaş döner ki bir günü 243 Dünya günü sürer. Güneş etrafındaki turu ise sadece 225 gün."},
    {"id": "gunes_isik", "kategori": "UZAY",
     "soru": "Güneş ışığı Dünya'ya kaç dakikada ulaşır?",
     "cevap": "Yaklaşık 8 dakika.",
     "aciklama": "Şu an gördüğün güneş ışığı aslında 8 dakika önce yola çıktı. Güneş bir anda sönse bunu 8 dakika boyunca fark edemezdik."},
    {"id": "ay_uzaklasiyor", "kategori": "UZAY",
     "soru": "Ay her yıl bizden uzaklaşıyor — peki ne kadar?",
     "cevap": "3,8 santimetre.",
     "aciklama": "Bu mesafe Ay'a bırakılan aynalara lazer tutularak milimetrik ölçülüyor. Uzak gelecekte tam güneş tutulmaları artık görülemeyecek."},
    {"id": "saturn_yuzer", "kategori": "UZAY",
     "soru": "Satürn'ü dev bir okyanusa atsan ne olurdu?",
     "cevap": "Yüzerdi!",
     "aciklama": "Satürn'ün ortalama yoğunluğu sudan düşüktür. Tabii onu taşıyacak büyüklükte bir okyanus bulmak ayrı bir dert."},
    {"id": "olympus_mons", "kategori": "UZAY",
     "soru": "Güneş Sistemi'nin en yüksek dağı hangi gezegende?",
     "cevap": "Mars'ta.",
     "aciklama": "Olympus Mons yaklaşık 22 kilometreyle Everest'in iki buçuk katından yüksektir; tabanı ise Fransa kadar geniştir."},
    {"id": "notron_yildizi", "kategori": "UZAY",
     "soru": "Bir çay kaşığı nötron yıldızı ne kadar ağır olurdu?",
     "cevap": "Milyarlarca ton.",
     "aciklama": "Nötron yıldızları o kadar yoğundur ki bir çay kaşığı maddesi yaklaşık bir dağ ağırlığındadır."},
    {"id": "en_sicak_gezegen", "kategori": "UZAY",
     "soru": "Güneş'e en yakın gezegen Merkür — peki en sıcağı o mu?",
     "cevap": "Hayır: Venüs.",
     "aciklama": "Venüs'ün kalın karbondioksit atmosferi ısıyı hapseder. Yüzeyi 460 derecedir — kurşunu eritecek kadar sıcak."},
    {"id": "uzayda_ses", "kategori": "UZAY",
     "soru": "Uzayda çığlık atsan ne duyulur?",
     "cevap": "Hiçbir şey.",
     "aciklama": "Ses yayılmak için maddeye ihtiyaç duyar. Uzay neredeyse tam bir boşluk olduğu için sesi taşıyacak hiçbir şey yoktur."},
    {"id": "astronot_boy", "kategori": "UZAY",
     "soru": "Astronotlar uzayda neden boy atar?",
     "cevap": "Omurgaları rahatladığı için.",
     "aciklama": "Yerçekimi olmayınca omurga sıkışmaz ve astronotlar 5 santimetre kadar uzar. Dünya'ya dönünce eski boylarına dönerler."},
    {"id": "ay_ayak_izi", "kategori": "UZAY",
     "soru": "Ay'daki ayak izleri ne kadar kalacak?",
     "cevap": "Milyonlarca yıl.",
     "aciklama": "Ay'da rüzgar ve yağmur olmadığı için 1969'da bırakılan izler bugün hâlâ ilk günkü gibi duruyor."},
    {"id": "gunes_galaksi_turu", "kategori": "UZAY",
     "soru": "Güneş Sistemi galakside sabit mi duruyor?",
     "cevap": "Hayır — saatte 800 bin kilometre hızla yol alıyor.",
     "aciklama": "Samanyolu'nun merkezi etrafındaki bir tam tur yaklaşık 230 milyon yıl sürüyor. Dinozorların yok oluşundan beri turun ancak dörtte birini tamamladık."},
    {"id": "agac_yildiz", "kategori": "UZAY",
     "soru": "Dünya'da mı daha çok ağaç var, Samanyolu'nda mı yıldız?",
     "cevap": "Ağaç!",
     "aciklama": "Dünya'da yaklaşık 3 trilyon ağaç var; Samanyolu'ndaki yıldız sayısı ise en fazla 400 milyar olarak hesaplanıyor."},

    # ── HAYVANLAR ─────────────────────────────────────
    {"id": "ahtapot_kalp", "kategori": "HAYVANLAR",
     "soru": "Ahtapotun kaç kalbi var?",
     "cevap": "Üç.",
     "aciklama": "İki kalbi solungaçlara, biri vücuda kan pompalar. Üstelik kanı bakır temelli olduğu için mavidir."},
    {"id": "denizyildizi_beyin", "kategori": "HAYVANLAR",
     "soru": "Denizyıldızının beyni nerede?",
     "cevap": "Hiçbir yerde — beyni yok.",
     "aciklama": "Vücuduna yayılmış sinir ağıyla hareket eder. Bazı türlerde kopan bir koldan yepyeni bir denizyıldızı bile oluşabilir."},
    {"id": "flamingo_pembe", "kategori": "HAYVANLAR",
     "soru": "Flamingolar neden pembe?",
     "cevap": "Yedikleri yüzünden.",
     "aciklama": "Aslında gri tüylerle doğarlar. Yedikleri karides ve alglerdeki pigmentler tüylerini zamanla pembeye boyar."},
    {"id": "baykus_goz", "kategori": "HAYVANLAR",
     "soru": "Baykuşlar gözlerini oynatabilir mi?",
     "cevap": "Hayır.",
     "aciklama": "Gözleri yuvalarına sabittir. Bunu telafi etmek için kafalarını 270 dereceye kadar çevirebilirler."},
    {"id": "kopekbaligi_agac", "kategori": "HAYVANLAR",
     "soru": "Köpekbalıkları mı daha eski, ağaçlar mı?",
     "cevap": "Köpekbalıkları.",
     "aciklama": "Köpekbalıkları yaklaşık 450 milyon yıldır var. İlk gerçek ağaçlar ise ondan yaklaşık 60 milyon yıl sonra ortaya çıktı."},
    {"id": "kedi_tatli", "kategori": "HAYVANLAR",
     "soru": "Kediler tatlıyı sever mi?",
     "cevap": "Sevemez — tadını alamaz.",
     "aciklama": "Kedilerde tatlı tat reseptörü genetik olarak çalışmaz. Pastana ilgi gösteriyorsa sebebi şeker değil, yağdır."},
    {"id": "yunus_uyku", "kategori": "HAYVANLAR",
     "soru": "Yunuslar uyurken nasıl boğulmuyor?",
     "cevap": "Beyninin yarısıyla uyuyor.",
     "aciklama": "Bir beyin yarımküresi uyurken diğeri nefes almayı kontrol eder. Bu yüzden tek gözleri açık uyurlar."},
    {"id": "fil_ziplayamaz", "kategori": "HAYVANLAR",
     "soru": "Zıplayamayan tek büyük kara memelisi hangisi?",
     "cevap": "Fil.",
     "aciklama": "Filler ağırlıkları ve bacak yapıları nedeniyle dört ayağını aynı anda yerden kesemez."},
    {"id": "sinek_kusu", "kategori": "HAYVANLAR",
     "soru": "Geriye doğru uçabilen tek kuş hangisi?",
     "cevap": "Sinek kuşu.",
     "aciklama": "Kanatlarını saniyede 50'den fazla çırparak 8 çizer; bu sayede havada asılı kalabilir ve geri geri uçabilir."},
    {"id": "su_aygiri_ter", "kategori": "HAYVANLAR",
     "soru": "Su aygırının kırmızı 'teri' ne işe yarar?",
     "cevap": "Doğal güneş kremi.",
     "aciklama": "Bu kırmızımsı salgı hem güneş ışınlarından korur hem de mikrop öldürücü özellik taşır."},
    {"id": "aksolotl", "kategori": "HAYVANLAR",
     "soru": "Hangi hayvan kopan bacağını yeniden çıkarabilir?",
     "cevap": "Aksolotl.",
     "aciklama": "Bu Meksika semenderi bacağını, kuyruğunu, hatta kalbinin ve beyninin bir kısmını bile yenileyebilir."},
    {"id": "tardigrad", "kategori": "HAYVANLAR",
     "soru": "Uzay boşluğunda hayatta kalabilen bir hayvan var mı?",
     "cevap": "Var: tardigrad.",
     "aciklama": "Su ayısı da denen bu milimetrelik canlı 2007'de uzay boşluğuna maruz bırakıldı ve hayatta kaldı. Donmaya, kaynamaya ve radyasyona da dayanıklıdır."},
    {"id": "yilan_dil", "kategori": "HAYVANLAR",
     "soru": "Yılanlar dillerini neden sürekli çıkarır?",
     "cevap": "Koku almak için.",
     "aciklama": "Dilleriyle havadaki molekülleri toplayıp damaklarındaki özel organla analiz ederler. Çatallı dil, kokunun hangi yönden geldiğini bile söyler."},
    {"id": "kopek_burun", "kategori": "HAYVANLAR",
     "soru": "Köpeklerin 'parmak izi' neresidir?",
     "cevap": "Burnu.",
     "aciklama": "Her köpeğin burun deseni, insan parmak izi gibi benzersizdir."},
    {"id": "karga_alet", "kategori": "HAYVANLAR",
     "soru": "Alet yapabilen bir kuş var mı?",
     "cevap": "Var: karga.",
     "aciklama": "Yeni Kaledonya kargaları dal parçalarını kanca şekline sokup kurtçuk avlar. Kargalar insan yüzlerini de yıllarca hatırlar."},
    {"id": "ari_dansi", "kategori": "HAYVANLAR",
     "soru": "Arılar birbirine adres tarifini nasıl verir?",
     "cevap": "Dans ederek.",
     "aciklama": "Sallanma dansının açısı yönü, süresi mesafeyi kodlar. Bu 'dans dili'nin çözülmesi Nobel Ödülü kazandırdı."},
    {"id": "penguen_tas", "kategori": "HAYVANLAR",
     "soru": "Bazı penguenler eşine ne hediye eder?",
     "cevap": "Çakıl taşı.",
     "aciklama": "Gentoo pengueni yuva için en pürüzsüz taşı seçip eşine sunar. Taş kabul edilirse yuvaya eklenir."},
    {"id": "mantis_karidesi", "kategori": "HAYVANLAR",
     "soru": "Denizlerin en hızlı yumruğu hangi hayvanda?",
     "cevap": "Mantis karidesinde.",
     "aciklama": "Yumruğu mermi ivmesiyle fırlar, çevresindeki suyu anlık kaynatacak kadar enerji açığa çıkarır ve akvaryum camını kırabilir."},

    # ── İNSAN VÜCUDU ──────────────────────────────────
    {"id": "mide_asidi", "kategori": "İNSAN VÜCUDU",
     "soru": "Mide asidin ne kadar güçlü?",
     "cevap": "Metali aşındıracak kadar.",
     "aciklama": "Mideni bu asitten koruyan şey, birkaç günde bir kendini tamamen yenileyen mukus tabakasıdır."},
    {"id": "hucre_sayisi", "kategori": "İNSAN VÜCUDU",
     "soru": "Vücudunda kaç hücre var?",
     "cevap": "Yaklaşık 37 trilyon.",
     "aciklama": "Üstelik vücudunda kendi hücrelerin kadar da bakteri yaşıyor. Sen aslında yürüyen bir ekosistemsin."},
    {"id": "kemik_celik", "kategori": "İNSAN VÜCUDU",
     "soru": "Kemik mi daha güçlü, çelik mi?",
     "cevap": "Ağırlığına göre kemik.",
     "aciklama": "Kemik, aynı ağırlıktaki çelikten daha fazla basınca dayanır. Küçük bir kemik parçası yüzlerce kilo yükü taşıyabilir."},
    {"id": "kalp_atisi", "kategori": "İNSAN VÜCUDU",
     "soru": "Kalbin günde kaç kez atıyor?",
     "cevap": "Yaklaşık 100 bin.",
     "aciklama": "Bir ömür boyunca bu sayı 2,5 milyarı bulur — hiç durmadan, hiç tatil yapmadan."},
    {"id": "burun_koku", "kategori": "İNSAN VÜCUDU",
     "soru": "Burnun kaç farklı kokuyu ayırt edebilir?",
     "cevap": "1 trilyondan fazla.",
     "aciklama": "2014'te yapılan bir araştırma, yıllardır ders kitaplarında yazan '10 bin koku' bilgisini çöpe attı."},
    {"id": "damar_uzunluk", "kategori": "İNSAN VÜCUDU",
     "soru": "Damarlarını uç uca eklesen nereye ulaşırdı?",
     "cevap": "Dünya'nın etrafını iki kez dolanırdı.",
     "aciklama": "Kılcal damarlar dahil toplam uzunluk yaklaşık 100 bin kilometredir."},
    {"id": "parmak_izi", "kategori": "İNSAN VÜCUDU",
     "soru": "Parmak izin ne zaman oluştu?",
     "cevap": "Sen doğmadan önce.",
     "aciklama": "Parmak izi ana rahminde üçüncü ayda şekillenir ve tek yumurta ikizlerinde bile birbirinden farklıdır."},
    {"id": "tuyler_diken", "kategori": "İNSAN VÜCUDU",
     "soru": "Tüylerin neden diken diken olur?",
     "cevap": "Atalarından kalma bir refleks.",
     "aciklama": "Kıllı atalarımızda bu refleks, vücudu kabartıp daha iri göstermeye ve ısınmaya yarıyordu. Bizde sadece anısı kaldı."},
    {"id": "dna_muz", "kategori": "İNSAN VÜCUDU",
     "soru": "Genlerinin yüzde kaçı muzla ortak?",
     "cevap": "Yaklaşık yarısı.",
     "aciklama": "Tüm canlılar ortak atadan geldiği için hücrenin temel işlerini yapan genler aynıdır. Şempanzeyle benzerliğimiz ise yüzde 98'i geçer."},
    {"id": "goz_kirpma", "kategori": "İNSAN VÜCUDU",
     "soru": "Günde kaç kez göz kırpıyorsun?",
     "cevap": "15 ila 20 bin kez.",
     "aciklama": "Bu, günde 10 dakikadan fazla 'karanlık' demek. Ama beynin bu boşlukları akıllıca sildiği için hiç fark etmezsin."},
    {"id": "en_kucuk_kemik", "kategori": "İNSAN VÜCUDU",
     "soru": "Vücudunun en küçük kemiği nerede?",
     "cevap": "Kulağında.",
     "aciklama": "Üzengi kemiği yaklaşık 3 milimetredir — pirinç tanesinden küçük. Ama o olmadan duyamazdın."},
    {"id": "mide_yenilenme", "kategori": "İNSAN VÜCUDU",
     "soru": "Miden neden kendini sindirmiyor?",
     "cevap": "Astarını sürekli yenilediği için.",
     "aciklama": "Mide astarı birkaç günde bir tamamen tazelenir. Bu yenilenme dursa, mide asidi mideyi sindirmeye başlardı."},

    # ── TARİH ─────────────────────────────────────────
    {"id": "kleopatra_zaman", "kategori": "TARİH",
     "soru": "Kleopatra piramitlere mi daha yakın yaşadı, Ay'a inişe mi?",
     "cevap": "Ay'a inişe.",
     "aciklama": "Büyük Piramit, Kleopatra'dan yaklaşık 2500 yıl önce yapılmıştı. Ay'a inişe ise sadece 2000 yıl vardı."},
    {"id": "oxford_aztek", "kategori": "TARİH",
     "soru": "Oxford Üniversitesi mi daha eski, Aztek İmparatorluğu mu?",
     "cevap": "Oxford.",
     "aciklama": "Oxford'da dersler 1096'da başlamıştı. Azteklerin başkenti Tenochtitlan ise 1325'te kuruldu."},
    {"id": "mamut_piramit", "kategori": "TARİH",
     "soru": "Mamutlar piramitler yapılırken hâlâ yaşıyor muydu?",
     "cevap": "Evet.",
     "aciklama": "Son yünlü mamutlar, Büyük Piramit'in tamamlanmasından yüzyıllar sonra bile Kuzey Buz Denizi'ndeki Wrangel Adası'nda yaşıyordu."},
    {"id": "en_kisa_savas", "kategori": "TARİH",
     "soru": "Tarihin en kısa savaşı ne kadar sürdü?",
     "cevap": "Yaklaşık 40 dakika.",
     "aciklama": "1896 İngiltere-Zanzibar Savaşı sabah 9'da başladı ve daha kahvaltı saati bitmeden sona erdi."},
    {"id": "eyfel_uzar", "kategori": "TARİH",
     "soru": "Eyfel Kulesi yazın neden uzar?",
     "cevap": "Demir genleştiği için.",
     "aciklama": "Sıcak günlerde kule 15 santimetre kadar uzar; güneş alan tarafı daha çok genleştiği için tepesi hafifçe eğilir bile."},
    {"id": "roma_idrar", "kategori": "TARİH",
     "soru": "Antik Roma'da idrar neden vergilendirildi?",
     "cevap": "Çünkü değerliydi.",
     "aciklama": "Amonyak içeren idrar, çamaşırhanelerde ve dericilikte kullanılıyordu. İmparator Vespasianus'un ünlü 'Para kokmaz' sözü buradan gelir."},
    {"id": "istanbul_tunel", "kategori": "TARİH",
     "soru": "Dünyanın en eski ikinci yeraltı treni hangi şehirde?",
     "cevap": "İstanbul'da.",
     "aciklama": "1875'te açılan Tünel, Karaköy ile Beyoğlu'nu bağlar. Ondan daha eski olan tek yeraltı hattı Londra'dadır."},
    {"id": "ketcap_ilac", "kategori": "TARİH",
     "soru": "Ketçap bir zamanlar ne olarak satıldı?",
     "cevap": "İlaç.",
     "aciklama": "1830'larda Amerika'da domates ketçabı, hazımsızlığa iyi geldiği iddiasıyla hap hâlinde satılıyordu."},
    {"id": "nintendo_1889", "kategori": "TARİH",
     "soru": "Nintendo hangi yıl kuruldu?",
     "cevap": "1889.",
     "aciklama": "Mario'dan neredeyse bir asır önce, Kyoto'da el yapımı oyun kartları üreten küçük bir dükkândı."},
    {"id": "secme_hakki", "kategori": "TARİH",
     "soru": "Türkiye'de kadınlar seçme hakkını Fransa'dan önce mi aldı?",
     "cevap": "Evet — tam 10 yıl önce.",
     "aciklama": "Türkiye'de bu hak 1934'te tanındı. Fransa 1944'ü, İsviçre ise 1971'i bekledi."},
    {"id": "olimpiyat_sanat", "kategori": "TARİH",
     "soru": "Olimpiyatlarda bir zamanlar hangi sıra dışı dalda madalya verildi?",
     "cevap": "Sanat.",
     "aciklama": "1912-1948 arasında resim, heykel, müzik, mimari ve edebiyat resmî olimpiyat dallarıydı."},

    # ── BİLİM ─────────────────────────────────────────
    {"id": "bal_bozulmaz", "kategori": "BİLİM",
     "soru": "Hiç bozulmayan yiyecek hangisi?",
     "cevap": "Bal.",
     "aciklama": "Mısır mezarlarında bulunan 3000 yıllık bal hâlâ yenilebilir durumdaydı. Düşük nemi ve asidik yapısı mikropları barındırmaz."},
    {"id": "muz_radyoaktif", "kategori": "BİLİM",
     "soru": "Muz gerçekten radyoaktif mi?",
     "cevap": "Evet — birazcık.",
     "aciklama": "İçindeki potasyum-40 doğal olarak radyoaktiftir. Ama zarar görmen için bir oturuşta milyonlarca muz yemen gerekir."},
    {"id": "simsek_sicaklik", "kategori": "BİLİM",
     "soru": "Şimşek mi daha sıcak, Güneş'in yüzeyi mi?",
     "cevap": "Şimşek — hem de 5 kat.",
     "aciklama": "Yıldırım kanalı yaklaşık 30 bin dereceye ulaşır. Güneş'in yüzeyi ise 5500 derecedir."},
    {"id": "uclu_nokta", "kategori": "BİLİM",
     "soru": "Su aynı anda hem kaynayıp hem donabilir mi?",
     "cevap": "Evet.",
     "aciklama": "Buna üçlü nokta denir: belirli bir basınç ve sıcaklıkta su; buz, sıvı ve buhar hâlinde aynı anda bulunur."},
    {"id": "helyum_ses", "kategori": "BİLİM",
     "soru": "Helyum sesi neden inceltir?",
     "cevap": "Ses, helyumda 3 kat hızlı yol alır.",
     "aciklama": "Hafif gazda ses tellerinin rezonansı tizleşir. Ama dikkat: saf helyum solumak oksijeni keser, tehlikelidir."},
    {"id": "dunya_cekirdek", "kategori": "BİLİM",
     "soru": "Dünya'nın çekirdeği ne kadar sıcak?",
     "cevap": "Güneş'in yüzeyi kadar.",
     "aciklama": "İç çekirdek yaklaşık 5500 derecedir. Ama üzerindeki muazzam basınç yüzünden eriyemez — katı bir demir topudur."},
    {"id": "bulut_agirlik", "kategori": "BİLİM",
     "soru": "Bir bulut ne kadar ağırdır?",
     "cevap": "Yaklaşık 500 ton.",
     "aciklama": "Orta boy bir kümülüs bulutu 100 fil ağırlığında su taşır. Düşmez, çünkü minik damlacıklar yükselen havayla asılı kalır."},
    {"id": "ada_lovelace", "kategori": "BİLİM",
     "soru": "Dünyanın ilk bilgisayar programcısı kimdi?",
     "cevap": "Bir kadın: Ada Lovelace.",
     "aciklama": "1843'te, ortada çalışan bir bilgisayar bile yokken, Babbage'ın makinesi için ilk algoritmayı yazdı."},
    {"id": "ilk_website", "kategori": "BİLİM",
     "soru": "Dünyanın ilk web sitesi hâlâ açık mı?",
     "cevap": "Evet.",
     "aciklama": "1991'de CERN'de yayınlanan info.cern.ch adresi bugün de ziyaret edilebilir."},
    {"id": "ilk_sms", "kategori": "BİLİM",
     "soru": "Tarihin ilk SMS'inde ne yazıyordu?",
     "cevap": "'Merry Christmas.'",
     "aciklama": "1992'de gönderildi. Alıcının telefonunda cevap yazma özelliği bile yoktu."},
    {"id": "bluetooth_viking", "kategori": "BİLİM",
     "soru": "Bluetooth adını nereden alır?",
     "cevap": "Bir Viking kralından.",
     "aciklama": "Danimarka'yı birleştiren Harald 'Mavi Diş' Gormsson'dan. Logo da onun adının baş harflerinin rünleridir."},
    {"id": "cam_akmaz", "kategori": "BİLİM",
     "soru": "Eski kilise camları altta daha kalın — cam aktığı için mi?",
     "cevap": "Hayır, bu bir efsane.",
     "aciklama": "Cam oda sıcaklığında akmaz. Eski üretim teknikleri camı eşit kalınlıkta yapamıyordu; ustalar kalın kenarı alta koyuyordu."},
    {"id": "kagit_katlama", "kategori": "BİLİM",
     "soru": "Bir kâğıdı en fazla kaç kez ikiye katlayabilirsin?",
     "cevap": "Genelde 7-8 kez.",
     "aciklama": "Her katlama kalınlığı ikiye katlar. 42 kez katlayabilseydin, kalınlığı Ay'a ulaşırdı."},

    # ── DÜNYA ─────────────────────────────────────────
    {"id": "afrika_yarimkure", "kategori": "DÜNYA",
     "soru": "Dört yarımkürede birden yer alan kıta hangisi?",
     "cevap": "Afrika.",
     "aciklama": "Hem ekvator hem başlangıç meridyeni Afrika'dan geçer; kıta kuzey, güney, doğu ve batı yarımkürelerin dördüne de yayılır."},
    {"id": "rusya_pluton", "kategori": "DÜNYA",
     "soru": "Rusya mı daha büyük, Plüton'un yüzeyi mi?",
     "cevap": "Rusya.",
     "aciklama": "Rusya 17 milyon kilometrekare; Plüton'un tüm yüzeyi ise yaklaşık 16,6 milyon kilometrekaredir."},
    {"id": "kanada_gol", "kategori": "DÜNYA",
     "soru": "Dünyadaki göllerin yarısından fazlası hangi ülkede?",
     "cevap": "Kanada'da.",
     "aciklama": "Kanada'da 800 binin üzerinde göl var — dünyadaki tüm doğal göllerin yarısından fazlası."},
    {"id": "sahra_kum", "kategori": "DÜNYA",
     "soru": "Sahra Çölü'nün tamamı kum mu?",
     "cevap": "Hayır — sadece dörtte biri.",
     "aciklama": "Geri kalanı çakıl, kaya ve dağlık alandır. Üstelik Sahra'ya zaman zaman kar bile yağar."},
    {"id": "avustralya_ay", "kategori": "DÜNYA",
     "soru": "Avustralya mı daha geniş, Ay mı?",
     "cevap": "Avustralya.",
     "aciklama": "Avustralya'nın doğu-batı genişliği yaklaşık 4000 kilometre; Ay'ın çapı ise 3474 kilometredir."},
    {"id": "olu_deniz", "kategori": "DÜNYA",
     "soru": "Dünyanın en alçak kara noktası neresi?",
     "cevap": "Ölü Deniz kıyısı.",
     "aciklama": "Deniz seviyesinin 430 metre altındadır. Suyu o kadar tuzludur ki batmak neredeyse imkânsızdır — ve aslında deniz değil, göldür."},
    {"id": "everest_buyume", "kategori": "DÜNYA",
     "soru": "Everest hâlâ büyüyor mu?",
     "cevap": "Evet — her yıl birkaç milimetre.",
     "aciklama": "Hindistan levhası Asya'ya çarpmaya devam ettikçe Himalayalar yükselmeyi sürdürüyor."},
    {"id": "pasifik_buyukluk", "kategori": "DÜNYA",
     "soru": "Pasifik Okyanusu ne kadar büyük?",
     "cevap": "Tüm karalardan daha büyük.",
     "aciklama": "165 milyon kilometrekareyle, dünyanın bütün kıtalarının toplam yüzölçümünden geniştir."},
    {"id": "istanbul_kita", "kategori": "DÜNYA",
     "soru": "İki kıtaya yayılan en büyük şehir hangisi?",
     "cevap": "İstanbul.",
     "aciklama": "Asya ve Avrupa'ya yayılır; her gün yüz binlerce insan işe giderken kıta değiştirir."},
    {"id": "finlandiya_sauna", "kategori": "DÜNYA",
     "soru": "Finlandiya'da kaç sauna var?",
     "cevap": "Yaklaşık 3 milyon.",
     "aciklama": "5,5 milyon nüfuslu ülkede neredeyse her iki kişiye bir sauna düşer. Meclis binasında bile sauna vardır."},
]
